In [2]:
import numpy as np
import pandas as pd
import re

ModuleNotFoundError: No module named 'numpy'

In [ ]:
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [ ]:
df = pd.read_csv('flats - flats.csv')

In [ ]:
df.head(1)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pearl Dental Clinic', 'Taneja Hospital', 'Dr. Ashok Jain', 'Dr. Madan Clinic', 'Geeta Nursing Home Gurgaon', 'Chiranjiv Hospital', 'Dev Man Kathuria Clinic', 'Aryan Hospital', 'Kr Dental Hub', 'Swastik Maternity and Medical Centre', 'Satyam Hospital Gurgaon', 'Ravi Clinic and Health Care Centre', 'D.R. Rajnis Gupta Clinic', 'Esic Hospital Gurugram', 'Gurgaon Eye Centre', 'Bindal Clinic', 'Shiv Mahima Patient Care Bureau', 'Shree Krishna Hospital Gurgaon', 'M.S Hospital', 'My Care Clinic', 'Ankur Clinic and Maternity Home', 'Triveni Hospital Gurgaon', 'Shri Gobind Hospital', 'Navjeevan Hospital and Maternity Centre', 'Lal Superspeciality Hospital', 'Sparsh Hospital Gurgaon', 'Prateek Nursing Home And Polyclinic', 'Jain Sant Phool Chand Ji Charitable Hospital', 'Sarvodya Hospital', 'Bhatnagar Maternity and Nursing Home', 'Tirath Ram Hospitals Pvt Ltd', 'Dr. Sarvejeet Singh', 'Centre For Sight Gurgaon New Railway Road', 'Dr. Ajay S. Gupta Clinic', 'Kidney Clinic', 'Mangalam Hospital and Heart Centre Gurgaon', 'Sethi Hospital Gurgaon', 'Shubham Hospital Gurgaon', 'Kharbanda Maternity and Nursing Home', 'Gupta Hospital Gurgaon', 'Dentecare - Multispeciality Dental Clinic', 'State bank of india', 'Hdfc bank', 'Kotak bank', 'Indian bank', 'Pizza Hut', 'St. Michaels Sr. Sec. School', 'Dronacharya Government College']","So with lift.Maa bhagwati residency is one of gurgaon's most sought after destination for apartments and this 2 bhk flat in krishna colony is your opportunity to be a part of this community. The flat occupies a carpet area of 900 sq.Ft. That consists of 2 bedrooms, 2 bathrooms and 1 balcony. This flat is situated on the top floor of this 4 floors tall residential building. This 1-5 years old property is available for immediate possession as the project is ready to move.","['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']","['Feng Shui / Vaastu Compliant', 'Security / Fire Alarm', 'Lift(s)', 'Water Storage', 'Visitor Parking']","['Environment4 out of 5', 'Safety4 out of 5', 'Lifestyle4 out of 5', 'Connectivity4 out of 5']"

In [ ]:
df[['price','area','areaWithType']].sample(5)

,price,area,areaWithType
1876,2.40,2875.0,Super Built up area 2875(267.1 sq.m.)Built Up area: 2456 sq.ft. (228.17 sq.m.)Carpet area: 2100 sq.ft. (195.1 sq.m.)
309,2.20,1549.0,Carpet area: 1549 (143.91 sq.m.)
2401,2.25,1549.0,Carpet area: 1549 (143.91 sq.m.)
2034,1.30,1410.0,Super Built up area 1420(131.92 sq.m.)Carpet area: 1410 sq.ft. (130.99 sq.m.)
1103,2.35,1997.0,Super Built up area 1997(185.53 sq.m.)Built Up area: 1950 sq.ft. (181.16 sq.m.)Carpet area: 1850 sq.ft. (171.87 sq.m.)

In [ ]:
def get_super_built_up_area(area):
    if isinstance(area, str):
        # your regex or logic here
        match = re.search(r"some pattern", area)
        if match:
            return match.group(1)  # example
    return None  # or 0, if that's what you want instead

In [ ]:
def get_area(text, area_type):
    if isinstance(text, str):
        # Replace with your actual regex logic
        match = re.search(fr'(\d+\.?\d*)\s*{area_type}', text)
        if match:
            return float(match.group(1))
    return None  # or 0, based on your needs

In [ ]:
def convert_to_sqft(areaWithType, value):
    if not isinstance(areaWithType, str):
        return None  # or 0 if you prefer
    # your logic here, for example:
    if "Sq. Meter" in areaWithType:
        return round(float(value) * 10.7639, 2)
    return value

In [ ]:
df['super_built_up_area'] = df['areaWithType'].apply(get_super_built_up_area)
df['super_built_up_area'] = df.apply(lambda x:convert_to_sqft(x['areaWithType'],x['super_built_up_area']), axis=1)

df['built_up_area'] = df['areaWithType'].apply(lambda x: get_area(x, 'Built Up area'))
df['built_up_area'] = df.apply(lambda x: convert_to_sqft(x['areaWithType'],x['built_up_area']), axis=1)

df['carpet_area'] = df['areaWithType'].apply(lambda x: get_area(x, 'Carpet area'))
df['carpet_area'] = df.apply(lambda x: convert_to_sqft(x['areaWithType'],x['carpet_area']), axis=1)

In [ ]:
df[['price','area','areaWithType','super_built_up_area','built_up_area','carpet_area']].sample(5)

,price,area,areaWithType,super_built_up_area,built_up_area,carpet_area
722,0.28,489.0,Carpet area: 489 (45.43 sq.m.),None,None,NaN
1927,1.32,1154.0,Super Built up area 1158(107.58 sq.m.),None,None,NaN
2606,0.30,362.0,Carpet area: 361.88 (33.62 sq.m.),None,None,NaN
1940,0.45,535.0,Super Built up area 597(55.46 sq.m.)Carpet area: 535.4 sq.ft. (49.74 sq.m.),None,None,NaN
2072,0.48,598.0,Super Built up area 598(55.56 sq.m.)Carpet area: 498 sq.ft. (46.27 sq.m.),None,None,NaN

In [ ]:
df.isnull().sum()

property_name             0
society                   1
price                    21
price_per_sqft           13
area                     21
areaWithType              9
bedRoom                   9
bathroom                  9
balcony                   9
additionalRoom            0
address                  15
floorNum                 11
facing                  890
agePossession            10
nearbyLocations         104
description               9
furnishDetails          814
features                423
rating                  341
super_built_up_area    3017
built_up_area          3017
carpet_area            3011
dtype: int64

In [ ]:
all_nan_index = df[
    (df['super_built_up_area'].isnull()) &
    (df['built_up_area'].isnull()) &
    (df['carpet_area'].isnull())
][['price','area','areaWithType','super_built_up_area','built_up_area','carpet_area']]
all_nan_df = df[
    (df['super_built_up_area'].isnull()) &
    (df['built_up_area'].isnull()) &
    (df['carpet_area'].isnull())
][['price', 'area', 'areaWithType', 'super_built_up_area', 'built_up_area', 'carpet_area']]

In [ ]:
def extract_plot_area(area_with_type):
  match = re.search(r'Plot area{\d+\.?\d+}',area_with_type)
  return float(match.group(1)) if match else None

In [ ]:
all_nan_df['built_up_area'] = all_nan_df['areaWithType'].astype(str).apply(extract_plot_area)

In [ ]:
all_nan_df.head()

,price,area,areaWithType,super_built_up_area,built_up_area,carpet_area
0,0.45,900.0,Carpet area: 900 (83.61 sq.m.),None,None,NaN
1,0.50,650.0,Carpet area: 650 (60.39 sq.m.),None,None,NaN
2,0.40,595.0,Carpet area: 595 (55.28 sq.m.),None,None,NaN
3,1.47,1200.0,Carpet area: 1200 (111.48 sq.m.),None,None,NaN
4,0.70,1345.0,Super Built up area 1345(124.95 sq.m.),None,None,NaN

In [ ]:
all_nan_df

      price      area  \
0      0.45     900.0
1      0.50     650.0
2      0.40     595.0
3      1.47    1200.0
4      0.70    1345.0
5      0.41     654.0
6      2.00    1500.0
7      1.80    2290.0
8      1.10    1350.0
9      4.75    2813.0
10     0.96     983.0
11     0.29     519.0
12     1.35    1945.0
13     0.95    1385.0
14     0.70    1300.0
15     3.95    2343.0
16     0.90     639.0
17     1.05     915.0
18      NaN       NaN
19     2.20    2100.0
20     1.01    1103.0
21     1.85    2150.0
22     0.86    1103.0
23     1.85    2025.0
24     2.85    2217.0
25      NaN       NaN
26     0.42     531.0
27     6.15    3355.0
28     6.25    2572.0
29     0.42     750.0
30     1.35    1056.0
31     1.60     594.0
32     3.25    3200.0
33     0.45     626.0
34     0.85    1300.0
35     0.75    1300.0
36     0.82    1180.0
37     1.80    2030.0
38     0.30     555.0
39     0.78    1365.0
40     2.00    1320.0
41     0.74    1194.0
42     3.20    2000.0
43     1.30    2038.0
44     0.25     700.0
45     0.95    1211.0
46     1.99    2727.0
47     1.05    1385.0
48     1.83    1829.0
49     2.25    2100.0
50     2.80    1650.0
51     1.60    1100.0
52     0.83    1530.0
53     0.83    1120.0
54     0.80    1250.0
55     1.25    2651.0
56     0.23     460.0
57     0.30     450.0
58     1.55    1570.0
59     0.79    1198.0
60     0.50     900.0
61     1.01    1443.0
62     0.95    1897.0
63     0.99    1260.0
64     1.10    1725.0
65     1.90    2144.0
66     1.00    2315.0
67     2.50    2250.0
68     1.10    1057.0
69     0.29     560.0
70     0.55     990.0
71     0.65    1370.0
72     0.50     532.0
73     0.32     580.0
74     0.93    1452.0
75     1.20    1423.0
76     0.30     640.0
77     0.56     822.0
78     2.70    2159.0
79     1.00    1950.0
80     1.45    1300.0
81     1.25    1423.0
82     0.46   58228.0
83     4.50    4246.0
84     0.64     985.0
85     0.28     743.0
86     3.87    2250.0
87     1.38    2177.0
88     0.43     650.0
89     0.28     884.0
90     1.10    1118.0
91     2.00    1433.0
92     0.90    1120.0
93     0.90    1120.0
94     1.75    1996.0
95     0.93    1080.0
96     1.80    2727.0
97     2.10    1789.0
98     2.00    1380.0
99     2.00    1562.0
100    1.29    1654.0
101    2.85    1828.0
102    1.10    1950.0
103    1.65    1200.0
104    0.24     324.0
105    2.10    2000.0
106    1.90    1929.0
107    1.10     958.0
108    0.32     711.0
109    1.70     965.0
110    0.32     524.0
111    0.45     581.0
112    1.20    1198.0
113    2.10    1310.0
114    0.45  642857.0
115    0.42     750.0
116    1.55    1557.0
117    1.30    1440.0
118    2.75    2597.0
119    1.25    1940.0
120    0.42     567.0
121    0.40     623.0
122    0.34     629.0
123    1.25    1423.0
124    1.50    1177.0
125    1.30    1400.0
126    1.60    2000.0
127    1.50    1276.0
128    1.50    1276.0
129    0.90    1259.0
130    1.50    1640.0
131    0.80     610.0
132    1.25    1690.0
133    0.26     482.0
134    0.42     531.0
135    2.50    1935.0
136    0.90    1950.0
137    0.42     591.0
138    0.50     650.0
139    0.90    1530.0
140    1.30    1910.0
141    1.70    1789.0
142    1.25    2016.0
143    2.91    4343.0
144    1.15    2000.0
145    1.20     958.0
146    1.50    1225.0
147    1.30    1751.0
148    1.75    1689.0
149    0.55     850.0
150    2.50    1838.0
151    0.43     810.0
152    0.80    1440.0
153    0.45    1000.0
154    0.70    1500.0
155    1.95    1350.0
156    0.45     626.0
157    1.70    1570.0
158    1.10    1800.0
159    0.50     520.0
160    2.80    1867.0
162    2.20    1630.0
163    0.90     951.0
164    0.40     514.0
165    1.35    1735.0
166    1.85    2300.0
167    0.25     380.0
168    0.88    1105.0
169    1.15    1744.0
170    1.60    1313.0
171    0.85    1252.0
172    0.75    1000.0
173    3.35    4500.0
174    1.50    1850.0
175    1.65    2600.0
176    2.00    2871.0
177    1.75    2800.0
178    0.90    1180.0
179    1.25    1865.0
180    1.00    1537.0
181    1.08    1756.0
182    2.15    2408.0
183    1.00     826.0
184    1.65    1262.0
185    1.79    2215.0
186    1.80    1370.0
187    1.45    1430.0
188    0.22     465.0
189    0.36     700.0
190    0.25     587.0
191    1.15    1534.0
192    1.65     946.0
193    2.90    2298.0
194    0.60    1320.0
195    2.40    2400.0
196    1.25    1262.0
197    2.15    1433.0
198    0.29     730.0
199    0.38     750.0
200    1.50    1200.0
201    0.39     950.0
202    1.60    2400.0
203    1.70    1999.0
204    3.25    2302.0
205    0.60     710.0
206    0.27    1000.0
207    0.95    1069.0
208    2.65    1433.0
209    0.36     471.0
210    0.55     600.0
211    1.32     780.0
212    0.59    1484.0
213    0.45     956.0
214    0.90    1446.0
215    1.40    1400.0
216    0.95    1452.0
217    3.00    1667.0
218    3.67    2040.0
219    3.85    5133.0
220    3.29    1828.0
221    2.33    1261.0
222    2.79    1969.0
223    3.40    2900.0
224    0.72     990.0
225    0.40     569.0
226    0.56    1364.0
227    1.10    1620.0
228    0.71    1310.0
229    0.78    1295.0
230    0.40     680.0
231    1.85    1579.0
232    1.10     903.0
233    1.41    1151.0
234    1.45    1945.0
235    2.20    1630.0
236    1.10    1110.0
237    2.05    2076.0
238    0.60    1200.0
239    0.80    1660.0
240    0.41     583.0
241    0.90    1622.0
242    0.54     917.0
243    0.82    1081.0
244    1.00    1485.0
245    1.85    2050.0
246    1.42    1775.0
247    0.55     600.0
248    2.29    1433.0
249    0.97     915.0
250    8.25    2946.0
251    0.30     675.0
252    1.65    1151.0
253    1.99    1260.0
254    1.00     800.0
255    4.25    1600.0
256    1.25    2500.0
257    0.95    1508.0
258    1.05    1350.0
259    4.10    2908.0
260    0.50     716.0
261    1.65    2800.0
262    1.60    1575.0
263    2.10    1527.0
264    0.90    2467.0
265    1.10    1415.0
266    0.92    1365.0
267    0.70    1260.0
268    0.99    1565.0
269    0.71    1171.0
270    0.88    1369.0
271    0.91    1326.0
272    1.25    1960.0
273    1.05     997.0
274    0.66    1310.0
275    1.83    1310.0
276    0.53    1104.0
277    0.80    1380.0
278    1.71    1425.0
279    0.65     700.0
280    1.30    1997.0
281    0.82    1523.0
282    5.70    1382.0
283    0.88     804.0
284    4.00    4061.0
285    1.93    2390.0
286    3.45    2600.0
287    1.70    2200.0
288    6.15    3844.0
289    1.40    1780.0
290    1.48    2000.0
291    3.25    4328.0
292    1.49    1750.0
293    0.30     652.0
294    3.49    2685.0
295    2.15    1508.0
296    1.40    1500.0
297    2.00    1407.0
298    2.30    1630.0
299    0.54     745.0
300    1.25    1806.0
302    1.25    1450.0
303    1.00    1100.0
304    1.70    2300.0
305    1.30    2786.0
306    2.12    1250.0
307    3.90    1174.0
308    3.00    2605.0
309    2.20    1549.0
310    1.35    1650.0
311    1.67    1590.0
312    0.90    1350.0
313    2.37    2061.0
314    1.98    2000.0
315    3.70    2100.0
316    4.67    2747.0
317    1.29    1572.0
318    3.65    2395.0
319    1.70    2200.0
320    6.15    3844.0
321    1.40    1780.0
322    1.48    2000.0
323    3.49    2685.0
324    2.15    1508.0
325    2.00    1407.0
326    0.54     745.0
327    1.25    1806.0
329    1.25    1450.0
330    1.00    1100.0
331    1.70    2300.0
332    1.30    2786.0
333    2.12    1250.0
334    3.00    2605.0
335    1.35    1650.0
336    0.90    1350.0
337    1.98    2000.0
338    3.70    2100.0
339    1.29    1572.0
340    5.60    2892.0
341    1.25    2143.0
342    1.27    1299.0
343    1.36    2079.0
344    1.00    1225.0
345    4.25    4553.0
346    1.80    1900.0
347    1.25    1895.0
348    0.27     458.0
349    5.50    3025.0
350    0.85    1990.0
351    1.07    1385.0
352    0.95     872.0
353    0.87     734.0
354    4.10    1752.0
355    1.27    1383.0
356    1.47    1150.0
357    3.45    2200.0
358    1.18    1565.0
359    1.55    1920.0
360    3.39    2358.0
361    1.54    1670.0
362    1.42    1650.0
363    1.30    1300.0
364    2.25    1550.0
365    3.50    2400.0
366    4.80    2500.0
367    0.78     969.0
368    0.88    1800.0
369    2.60    2598.0
370    3.40    2470.0
371    2.90    2003.0
372    0.70    1505.0
373    1.50    1540.0
374    1.28    1340.0
375    2.51    1696.0
376    6.50    3500.0
377    3.63    2503.0
378    1.85    2150.0
379    2.45    2875.0
380    1.38    2120.0
381    5.90    5350.0
382    3.00    4891.0
383    2.01    1759.0
384    2.10    1759.0
385    4.25    3200.0
386    2.55    2070.0
387    2.00    2350.0
388    3.25    2537.0
389    1.60    2045.0
390    1.50    1917.0
391    3.75    2510.0
392    0.95    1416.0
393    1.40    1300.0
394    1.56    1929.0
395    1.35    1650.0
396    1.40    1349.0
397    2.26    1650.0
398    1.20    1492.0
399    2.08    2080.0
400    1.75    2408.0
401    2.99    2527.0
402    2.10    1473.0
403    2.87    2411.0
404    2.35    1777.0
405    3.00    2500.0
406    6.00    4400.0
407    2.35    1650.0
408    1.90    3344.0
409    0.72    1475.0
410    0.65    1526.0
411    2.34    2092.0
412    2.57    1650.0
413    1.71    2191.0
414    3.79    3830.0
415    2.05    2600.0
416    5.20    2979.0
417    3.20    1800.0
418    0.69     949.0
419    3.75    2802.0
420    3.65    2965.0
421    5.49    4739.0
422    1.05    2095.0
423    3.35    2525.0
424    2.40    2086.0
425    1.71    2250.0
426    6.30    4095.0
427    2.20    2318.0
428    3.25    3400.0
429   11.25    3980.0
430    3.30    2400.0
431    1.51    1919.0
432    1.38    1023.0
433    4.60    2500.0
434    1.40    1650.0
435    3.50    1975.0
436    0.99    1790.0
437    2.65    1650.0
438    2.40    1944.0
439    1.65    2150.0
440    1.25    1806.0
441    4.00    2690.0
442    1.80    1900.0
443    1.75    1574.0
444    2.35    1650.0
445    7.15    4337.0
446    1.64    1950.0
447    2.80    1650.0
448    6.75    3160.0
449    3.50    2400.0
450    4.60    1717.0
451    2.25    1800.0
452    2.20    2092.0
453    2.85    2606.0
454    1.76    2215.0
455    1.00    1385.0
456    3.60    2851.0
457    1.78    2408.0
458    0.98    1620.0
459    2.82    2200.0
460    3.21    2000.0
461    1.90    1027.0
462    1.19    2162.0
463    1.35    1790.0
464    1.80    2000.0
465    1.35    1790.0
466    1.70    2545.0
467    1.60    2425.0
468    2.65    2019.0
469    0.55     950.0
470    1.40    1023.0
471    1.26    1565.0
472    1.70    2768.0
473    4.10    1459.0
474    1.01    1250.0
475    1.45    1997.0
476    1.60    1910.0
477    2.99    2000.0
478    1.90    1942.0
479    1.75    1395.0
480    1.30    1818.0
481    2.95    2411.0
482    3.40    2358.0
483    3.32    2358.0
484    0.95    1415.0
485    1.55    1124.0
486    1.54    1424.0
487    2.45    2018.0
488    2.60    1715.0
489    1.83    2405.0
490    1.09    1636.0
491    1.87    2404.0
492    1.05    1704.0
493    1.77    2408.0
494    2.20    2018.0
495    0.60     735.0
496    1.80    3000.0
497    0.64    1526.0
498    0.75    2267.0
499    4.95    3112.0
500    4.25    3763.0
501    5.31    4739.0
502    1.40    1650.0
503    2.80    2441.0
504    4.10    3880.0
505    3.40    3400.0
506    3.05    2385.0
507    4.25    3250.0
508    1.16    1660.0
509    3.55    5201.0
510    1.80    1889.0
511    1.75    1128.0
512    1.20     824.0
513    1.52    1650.0
514    1.55    2250.0
515    2.40    2103.0
516    2.35    2103.0
517    2.28    2103.0
518    1.10    2265.0
519    2.30    2103.0
520    1.35    2361.0
521    2.45    2450.0
522    0.90    1534.0
523    2.80    1975.0
524    1.40    1376.0
525    1.36    1779.0
526    0.98    1408.0
527    0.56     649.0
528    2.20    2900.0
529    1.20    2650.0
530    1.33    1550.0
531    0.87    1578.0
532    1.09    1635.0
533    3.00    1950.0
534    1.75    1900.0
535    1.75    1900.0
536    3.80    2800.0
537    3.50    2995.0
538    1.78    2215.0
539    1.08    1640.0
540    2.03    2808.0
541    1.12    1736.0
542    2.00    3040.0
543    1.04    1741.0
544    1.25    2120.0
545    2.05    1350.0
546    3.19    2625.0
547    3.85    2905.0
548    3.20    2625.0
549    0.89    2037.0
550    0.49    1125.0
551    1.65    1950.0
552    2.35    2660.0
553    1.40    1810.0
554    0.97    1790.0
555    2.35    2069.0
556    3.32    2635.0
557    1.25    1980.0
558    2.80    2047.0
559    4.70    2380.0
560    1.30    1650.0
561    0.62    1239.0
562    0.80    1654.0
563    1.73    1900.0
564    4.45    4200.0
565    2.30    2660.0
566    2.20    2103.0
567    2.12    2103.0
568    2.25    2103.0
569    1.90    2325.0
570    4.40    3500.0
571    1.75    2300.0
572    2.80    2350.0
573    4.63    3090.0
574    1.32    1507.0
575    1.16    1743.0
576    0.27     489.0
577    0.28     493.0
578    1.79    2025.0
579    1.55    1950.0
580    1.55    1929.0
581    3.35    2000.0
582    3.50    2125.0
583    4.80    2895.0
584    1.50    1850.0
585    2.78    2690.0
586    2.25    2428.0
587    2.55    2150.0
588    1.25    1600.0
589    0.85     950.0
590    5.25    5800.0
591    1.30    1351.0
592    0.75    1050.0
593    3.65    2698.0
594    1.65    2903.0
595    1.25    1930.0
596    1.42    2919.0
597    1.27    2310.0
598    1.65    2215.0
599    1.24    1755.0
600    2.70    2705.0
601    1.98    2191.0
602    2.50    1800.0
603    2.29    1650.0
604    2.98    2047.0
605    1.35    1095.0
606    1.37    1500.0
607    1.55    2000.0
608    4.25    3200.0
609    1.28    1877.0
610    1.95    1128.0
611    2.35    2660.0
612    5.00    2700.0
613    0.99    1800.0
614    1.95    2727.0
615    3.30    2700.0
616    4.75    3410.0
617    1.50    1200.0
618    1.54    2364.0
619    1.27    1930.0
620    1.17    1744.0
621    1.80    1300.0
622    0.80    1361.0
623    1.76    1776.0
624    2.22    1600.0
625    1.24    1000.0
626    1.12    1567.0
627    1.90    1350.0
628    1.35    1150.0
629    2.22    2095.0
630    0.90    1283.0
631    1.75    2150.0
632    0.67    1150.0
633    2.95    2436.0
634    2.04    1395.0
635    2.24    3434.0
636    1.31    1617.0
637    1.70     809.0
638    1.19    1600.0
639    1.75    1500.0
640    1.12    1735.0
641    0.92    2287.0
642    0.90    2287.0
643    2.30    2450.0
644    1.58    1733.0
645    4.25    3880.0
646    1.68    1520.0
647    4.55    3130.0
648    2.85    2350.0
649    2.35    1935.0
650    2.30    2092.0
651    2.26    2100.0
652    4.78    3090.0
653    2.00    2400.0
654    3.75    2800.0
655    6.16    3000.0
656    5.30    2189.0
657    0.75    1342.0
658    1.25    1490.0
659    2.00    2360.0
660    1.30    1490.0
661    1.75    2000.0
662    2.00    3200.0
663    1.78    1950.0
664    1.15    1534.0
665    1.65    2100.0
666    0.21     302.0
667    2.75    2000.0
668    2.72    2350.0
669    2.40    2086.0
670    4.10    2987.0
671    1.12    1802.0
672    0.65    1350.0
673    7.50   10000.0
674   11.00    3100.0
675    1.26    1702.0
676    1.80    2492.0
677    5.90    3375.0
678    2.90    2383.0
679    1.59    1929.0
680    2.21    2132.0
681    1.48    1900.0
682    0.98     734.0
683    2.04    1450.0
684    1.50    2560.0
685    1.49    2560.0
686    1.20    2120.0
687    0.86    1375.0
688    0.90    1986.0
689    2.00    1965.0
690    1.85    2010.0
691    2.65    1766.0
692    1.50    1650.0
693    1.75    1745.0
694    1.32    1550.0
695    0.80    1320.0
696    1.20    1758.0
697    6.50    4337.0
698    1.17    1760.0
699    1.15    1900.0
700    2.48    1760.0
701    1.35    1400.0
702    1.15    1325.0
703    2.95    2003.0
704    3.40    2358.0
705    2.80    2048.0
706    2.15    2095.0
707    1.76    1721.0
708    3.45    2950.0
709    3.30    3350.0
710    1.75    2290.0
711    2.78    3150.0
712    1.42    2355.0
713    2.40    2276.0
714    2.28    2779.0
715    1.90    1381.0
716    3.25    2072.0
717    1.60    2545.0
718    4.45    6500.0
719    0.82    1366.0
720    0.50     645.0
721    0.52     645.0
722    0.28     489.0
723    0.29     489.0
724    0.97    1050.0
725    0.80    1366.0
726    1.45    1023.0
727    0.55     850.0
728    1.10    1550.0
729    1.40    1484.0
730    1.42    1578.0
731    2.95    2576.0
732    2.60    2441.0
733    1.10    1762.0
734    0.75    1366.0
735    1.30    1457.0
736    1.49    2361.0
737    1.19    1171.0
738    1.15    1616.0
739    0.99    1488.0
740    0.78    1245.0
741    1.15    1980.0
742    0.80    1961.0
743    2.20    2149.0
744    1.55    1800.0
745    1.55    1578.0
746    0.90    1500.0
747    0.90    2089.0
748    0.85    2150.0
749    3.00    2403.0
750    2.12    1365.0
751    1.05    1822.0
752    1.65    2408.0
753    1.50    1963.0
754    3.40    2358.0
755    3.50    2358.0
756    3.15    2452.0
757    5.25    2575.0
758    2.78    2047.0
759    0.72    1600.0
760    1.55    2000.0
761    1.50    1185.0
762    3.05    1875.0
763    3.83    1775.0
764    2.25    1650.0
765    1.40    1950.0
766    3.75    2802.0
767    1.51    1976.0
768    2.70    2305.0
769    3.35    2692.0
770    1.50    1400.0
771    2.20    2660.0
772    2.55    2273.0
773    0.45     598.0
774    1.18    1735.0
775    0.85    1270.0
776    1.49    1963.0
777    6.50    3390.0
778    1.18    2266.0
779    0.80    1523.0
780    1.42    1600.0
781    5.00    3000.0
782    1.72    1929.0
783    1.95    1400.0
784    0.75    1340.0
785    1.72    2191.0
786    2.50    3198.0
787    1.70    2025.0
788    1.14    1336.0
789    1.35    1345.0
790    0.27     446.0
791    1.40    2356.0
792    1.25    1930.0
793    1.18    1100.0
794    1.10    1150.0
795    1.21    1943.0
796    3.45    3400.0
797    1.95    1852.0
798    3.65    2950.0
799    2.30    1946.0
800    3.40    2200.0
801    1.14    1746.0
802    0.96    1461.0
803    3.05    1960.0
804    2.35    1760.0
805    1.05    1550.0
806    1.02    1160.0
807    1.08    1630.0
808    1.75    1676.0
809    2.45    2271.0
810    6.00    6565.0
811    1.68    1745.0
812    1.26    1255.0
813    1.82    2020.0
814    2.58    2200.0
815    1.75    1668.0
816    2.60    1711.0
817    2.90    2003.0
818    1.40    2361.0
819    2.95    3150.0
820    2.25    2585.0
821    1.40    1750.0
822    1.26    1926.0
823    1.70    1971.0
824    1.43    1582.0
825    1.30    1569.0
826    1.32    1569.0
827    2.00    2010.0
828    1.43    1609.0
829    3.46    2872.0
830    2.25    2132.0
831    1.70    1745.0
832    1.80    2545.0
833    1.35    1880.0
834    5.40    2979.0
835    1.55    2100.0
836    1.60    1682.0
837    2.09    2400.0
838    1.75    2200.0
839    1.38    1720.0
840    2.25    1650.0
841    2.40    2103.0
842    1.72    1900.0
843    0.88    1854.0
844    3.15    3750.0
845    1.72    1811.0
846    1.47    1342.0
847    1.10    1802.0
848    1.32    2193.0
849    1.30    2350.0
850    1.35    2350.0
851    3.00    2764.0
852    1.60    1929.0
853    3.00    2383.0
854    0.90    2588.0
855    1.75    2200.0
856    2.00    1852.0
857    1.80    1692.0
858    1.60    1745.0
859    1.40    1450.0
860    1.80    2042.0
861    2.70    2350.0
862    1.55    1930.0
863    1.15    1790.0
864    1.49    1650.0
865    1.91    2000.0
866    1.05    1225.0
867    2.14    2875.0
868    1.02    1415.0
869    0.56     655.0
870    2.50    1550.0
871    2.00    1700.0
872    2.20    1717.0
873    1.65    2003.0
874    1.60    1669.0
875    0.85    1300.0
876    1.40    1650.0
877    2.09    1430.0
878    2.51    2061.0
879    1.69    2125.0
880    0.98    1414.0
881    2.00    2779.0
882    1.95    1955.0
883    2.10    1362.0
884    1.55    2000.0
885    1.98    2182.0
886    2.05    2400.0
887    1.40    2300.0
888    1.40    1750.0
889    2.36    2570.0
890    1.65    1550.0
891    2.65    1950.0
892    2.63    2750.0
893    2.25    2150.0
894    2.55    1950.0
895    1.15    1481.0
896    1.45    2000.0
897    2.60    2950.0
898    1.55    1650.0
899    1.20    1420.0
900    1.55    1950.0
901    1.65    1950.0
902    1.05    1640.0
903    1.29    1430.0
904    0.56     706.0
905    1.26    1650.0
906    1.91    3800.0
907    2.20    3900.0
908    1.98    2398.0
909    1.11    1620.0

In [ ]:
import re

def extract_sqft(area_with_type):
    if isinstance(area_with_type, str):
        match = re.search(r'(\d+\.?\d*)\s*\(', area_with_type)
        if match:
            return float(match.group(1))
    return None

In [ ]:

all_nan_df['built_up_area'] = all_nan_df['areaWithType'].apply(extract_sqft)

In [ ]:
print(all_nan_df['areaWithType'].head())

0            Carpet area: 900 (83.61 sq.m.)
1            Carpet area: 650 (60.39 sq.m.)
2            Carpet area: 595 (55.28 sq.m.)
3          Carpet area: 1200 (111.48 sq.m.)
4    Super Built up area 1345(124.95 sq.m.)
Name: areaWithType, dtype: object

In [ ]:
def categorize_age_possession(value):
    if pd.isna(value):
        return "Undefined"
    if "0 to 1 Year Old" in value or "within 6 months" in value or "within 3 months" in value:
        return "new Property"
    if "5 to 10 Year Old" in value:
        return "Moderately Old"
    if "10+ Year Old" in value:
        return "Old Property"
    if "Under Construction" in value or "By" in value:
        return "Under Construction"
    try:
        int(value.split(" ")[-1])
        return "Under Construction"
    except:
        return "Undefined"

In [ ]:
df['agePossession'] = df['agePossession'].apply(categorize_age_possession)

In [ ]:
df['agePossession'].value_counts()

agePossession
Undefined             1944
new Property           443
Moderately Old         361
Old Property           137
Under Construction     132
Name: count, dtype: int64

In [ ]:
df.sample(5)[['furnishDetails','features']]

,furnishDetails,features
1435,NaN,"['Feng Shui / Vaastu Compliant', 'Security / Fire Alarm', 'Intercom Facility', 'Lift(s)', 'Maintenance Staff', 'Water Storage', 'Park', 'Visitor Parking']"
22,[],NaN
995,"['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Geyser', '8 Light', '1 Chimney', '1 Modular Kitchen', '1 Curtains', 'No AC', 'No Bed', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']","['Centrally Air Conditioned', 'Water purifier', 'Security / Fire Alarm', 'Power Back-up', 'Feng Shui / Vaastu Compliant', 'Private Garden / Terrace', 'Intercom Facility', 'Lift(s)', 'High Ceiling Height', 'Maintenance Staff', 'False Ceiling Lighting', 'Water Storage', 'Separate entry for servant room', 'No open drainage around', 'Piped-gas', 'Internet/wi-fi connectivity', 'Recently Renovated', 'Visitor Parking', 'Swimming Pool', 'Park', 'Security Personnel', 'Natural Light', 'Airy Rooms', 'Spacious Interiors', 'Waste Disposal', 'Rain Water Harvesting', 'Water softening plant', 'Shopping Centre', 'Fitness Centre / GYM', 'Club house / Community Center']"
2195,"['1 Fan', '1 Light', '1 AC', '1 Modular Kitchen', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']","['Security / Fire Alarm', 'Feng Shui / Vaastu Compliant', 'Lift(s)', 'High Ceiling Height', 'Maintenance Staff', 'Water Storage', 'No open drainage around', 'Visitor Parking', 'Swimming Pool', 'Park', 'Security Personnel', 'Low Density Society', 'Shopping Centre', 'Fitness Centre / GYM', 'Waste Disposal', 'Rain Water Harvesting', 'Club house / Community Center']"
1862,[],"['Feng Shui / Vaastu Compliant', 'Security / Fire Alarm', 'Intercom Facility', 'Lift(s)', 'Maintenance Staff', 'Water Storage', 'Park', 'Visitor Parking']"

In [ ]:
all_furnishings = []
for detail in df['furnishDetails'].dropna():
    furnishings = detail.replace('[','').replace(']','').replace("'","").split(',')
    all_furnishings.extend(furnishings)
unique_furnishings = list(set(all_furnishings))

In [ ]:
import re

def get_furnishing_count(details, furnishing):
    if isinstance(details, str):
        if f"No {furnishing}" in details:
            return 0
        pattern = re.compile(rf"(\d+)\s+{re.escape(furnishing)}", re.IGNORECASE)
        match = pattern.search(details)
        if match:
            return int(match.group(1))
        elif furnishing.lower() in details.lower():
            return 1
    return 0

In [ ]:
columns_to_include = [re.sub(r'No |\d+','',furnishing).strip() for furnishing in unique_furnishings]
columns_to_include =  list(set(columns_to_include))
columns_to_include = [furnishing for furnishing in columns_to_include if furnishing]

In [ ]:
for furnishing in columns_to_include:
    df[furnishing] = df['furnishDetails'].apply(lambda x: get_furnishing_count(x, furnishing))
furnishings_df = df[['furnishDetails'] + columns_to_include]

In [ ]:
furnishings_df.shape
furnishing_counts = pd.DataFrame({
    item: furnishings_df.apply(lambda x: extract_counts(x, item)) for item in furnishing_items
})

NameError: name 'furnishing_items' is not defined

In [ ]:
furnishings_df.head()
def extract_counts(furnishings, item):
    if not isinstance(furnishings, list):
        return 0
    for entry in furnishings:
        if item in entry:
            match = re.search(r'(\d+)', entry)
            if match:
                return int(match.group(1))
            else:
                return 0
    return 0

In [ ]:
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.preprocessing import StandardScaler

# Drop non-numeric column
numeric_furnishings = furnishings_df.drop(columns=['furnishDetails'])

# Now scale
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_furnishings)

# Optionally convert back to DataFrame
scaled_df = pd.DataFrame(scaled_data, columns=numeric_furnishings.columns)

print(scaled_df.head())

        Fan   Chimney  Dining Table  Wardrobe  Microwave  Exhaust Fan  \
0  0.440637 -0.641627     -0.185153 -0.018214  -0.236723    -0.667026
1  0.818523  1.492650     -0.185153  1.216623  -0.236723     1.499192
2 -0.693020 -0.641627     -0.185153 -0.635632  -0.236723    -0.667026
3 -0.693020 -0.641627     -0.185153 -0.635632  -0.236723    -0.667026
4 -0.693020 -0.641627     -0.185153 -0.635632  -0.236723    -0.667026

      Light  Water Purifier       Bed    Geyser  Modular Kitchen  Curtains  \
0  0.018816       -0.307092 -0.166057 -0.568185        -0.813230 -0.256369
1 -0.126743       -0.307092 -0.166057  0.125829         1.229664  0.784633
2 -0.563420       -0.307092 -0.166057 -0.568185        -0.813230 -0.256369
3 -0.563420       -0.307092 -0.166057 -0.568185        -0.813230 -0.256369
4 -0.563420       -0.307092 -0.166057 -0.568185        -0.813230 -0.256369

         AC    Stove  Washing Machine        TV    Fridge     Sofa
0 -0.585605 -0.36751        -0.214748 -0.142154 -0.227931 -0.20264
1 -0.585605 -0.36751        -0.214748 -0.142154 -0.227931 -0.20264
2 -0.585605 -0.36751        -0.214748 -0.142154 -0.227931 -0.20264
3 -0.585605 -0.36751        -0.214748 -0.142154 -0.227931 -0.20264
4 -0.585605 -0.36751        -0.214748 -0.142154 -0.227931 -0.20264

In [ ]:
wcss_reduced = []

for i in range(1,11):
    kmeans = KMeans(n_clusters=i,init='k-means++',random_state=42)
    kmeans.fit(scaled_data)
    wcss_reduced.append(kmeans.inertia_)

In [ ]:
plt.figure(figsize=(12,8))
plt.plot(range(1,11),wcss_reduced, marker='o',linestyle='--')
plt.title('Elbow Method For Optimal number of Clusters (Reduced Range)')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.grid(True)
plt.show()

NameError: name 'wcss_reduced' is not defined

In [ ]:
scaled_data

array([[ 0.44063703, -0.64162727, -0.18515344, ..., -0.14215397,
        -0.22793109, -0.20263959],
       [ 0.81852275,  1.49264998, -0.18515344, ..., -0.14215397,
        -0.22793109, -0.20263959],
       [-0.6930201 , -0.64162727, -0.18515344, ..., -0.14215397,
        -0.22793109, -0.20263959],
       ...,
       [-0.6930201 , -0.64162727, -0.18515344, ..., -0.14215397,
        -0.22793109, -0.20263959],
       [ 3.08583702,  1.49264998, -0.18515344, ..., -0.14215397,
         4.38729098,  4.93486992],
       [ 1.57429417,  1.49264998, -0.18515344, ..., -0.14215397,
         4.38729098, -0.20263959]])

In [ ]:
furnishings_df.head()

,furnishDetails,Fan,Chimney,Dining Table,Wardrobe,Microwave,Exhaust Fan,Light,Water Purifier,Bed,Geyser,Modular Kitchen,Curtains,AC,Stove,Washing Machine,TV,Fridge,Sofa
0,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']",3,0,0,1,0,0,4,0,0,0,0,0,0,0,0,0,0,0
1,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Geyser', '3 Light', '1 Curtains', '1 Chimney', '1 Modular Kitchen', 'No AC', 'No Bed', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']",4,1,0,3,0,1,3,0,0,1,1,1,0,0,0,0,0,0
2,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,[],0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
df=df.iloc[:,:-18]

In [ ]:
n_clusters = 3
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
kmeans.fit(scaled_data)
cluster_assignments = kmeans.predict(scaled_data)
df['furnishing_type'] = cluster_assignments

In [ ]:
df.sample(5)[['furnishDetails','furnishing_type']]

,furnishDetails,furnishing_type
1934,"['1 Water Purifier', '6 Fan', '1 Fridge', '1 Exhaust Fan', '1 Dining Table', '4 Geyser', '1 Stove', '25 Light', '1 Chimney', '5 Curtains', '5 AC', '1 Modular Kitchen', '4 Wardrobe', '1 Sofa', '1 Microwave', 'No Bed', 'No TV', 'No Washing Machine']",2
1003,NaN,0
2718,[],0
2883,NaN,0
1731,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Fan', 'No Geyser', 'No Light', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Wardrobe', 'No Washing Machine', 'No Water Purifier']",0

In [ ]:
df[['features']].sample(5)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              features
2765                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               NaN
2627                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               NaN
2780                                                                                                                                                                                                                                                                                                                                       ['Feng Shui / Vaastu Compliant', 'Intercom Facility', 'Lift(s)', 'Maintenance Staff', 'Piped-gas', 'Visitor Parking', 'Swimming Pool', 'Park', 'Security Personnel', 'Natural Light', 'Internet/wi-fi connectivity', 'Airy Rooms', 'Low Density Society', 'Fitness Centre / GYM', 'Rain Water Harvesting', 'Club house / Community Center']
580   ['Centrally Air Conditioned', 'Water purifier', 'Security / Fire Alarm', 'Feng Shui / Vaastu Compliant', 'Private Garden / Terrace', 'Intercom Facility', 'Lift(s)', 'High Ceiling Height', 'Maintenance Staff', 'False Ceiling Lighting', 'Water Storage', 'No open drainage around', 'Bank Attached Property', 'Piped-gas', 'Internet/wi-fi connectivity', 'Recently Renovated', 'Visitor Parking', 'Swimming Pool', 'Park', 'Security Personnel', 'Natural Light', 'Airy Rooms', 'Spacious Interiors', 'Low Density Society', 'Waste Disposal', 'Rain Water Harvesting', 'Water softening plant', 'Shopping Centre', 'Fitness Centre / GYM', 'Club house / Community Center']
1774                                                                                                                                                                                                                                          ['Security / Fire Alarm', 'Power Back-up', 'Feng Shui / Vaastu Compliant', 'Intercom Facility', 'Lift(s)', 'Maintenance Staff', 'False Ceiling Lighting', 'Water Storage', 'Piped-gas', 'Visitor Parking', 'Swimming Pool', 'Park', 'Security Personnel', 'Internet/wi-fi connectivity', 'Shopping Centre', 'Fitness Centre / GYM', 'Waste Disposal', 'Rain Water Harvesting', 'Club house / Community Center', 'Water softening plant']

In [ ]:
df['features'].isnull().sum()

np.int64(423)

In [ ]:
import pandas as pd
app_df = pd.read_csv('appartments.csv')
app_df.head(2)

,furnishDetails,Chimney,Curtains,Wardrobe,Exhaust Fan,Modular Kitchen,Sofa,Geyser,TV,Dining Table,Fridge,Water Purifier,Stove,AC,Fan,Light,Bed,Microwave,Washing Machine
0,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']",0,0,1,0,0,0,0,0,0,0,0,0,0,3,4,0,0,0
1,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Geyser', '3 Light', '1 Curtains', '1 Chimney', '1 Modular Kitchen', 'No AC', 'No Bed', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']",1,1,3,1,1,0,1,0,0,0,0,0,0,4,3,0,0,0

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer
import ast
df['features_list'] = df['features'].apply(
    lambda x: ast.literal_eval(x) if pd.notnull(x) and str(x).startswith('[') else []
)



from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
features_binary_matrix = mlb.fit_transform(df['features_list'])

# Convert to DataFrame with correct column names
features_binary_df = pd.DataFrame(features_binary_matrix, columns=mlb.classes_)


features_binary_df.sample(5)
weights = {
    'AC': 3,
    'Bed': 2,
    'Chimney': 1,
    'Curtains': 1,
    'Dining Table': 2,
    'Exhaust Fan': 1,
    'Fan': 1,
    'Fridge': 2,
    'Geyser': 2,
    'Light': 1,
    'Microwave': 2,
    'Modular Kitchen': 3,
    'Sofa': 2,
    'Stove': 1,
    'TV': 2,
    'Wardrobe': 2,
    'Washing Machine': 2,
    'Water Purifier': 2
}

In [ ]:
luxury_score = features_binary_df[list(weights.keys())].multiply(
    list(weights.values()), axis=1
).sum(axis=1)

KeyError: "None of [Index(['AC', 'Bed', 'Chimney', 'Curtains', 'Dining Table', 'Exhaust Fan',\n       'Fan', 'Fridge', 'Geyser', 'Light', 'Microwave', 'Modular Kitchen',\n       'Sofa', 'Stove', 'TV', 'Wardrobe', 'Washing Machine', 'Water Purifier'],\n      dtype='object')] are in the [columns]"

In [ ]:
print(features_binary_df.columns.tolist())

['Airy Rooms', 'Bank Attached Property', 'Centrally Air Conditioned', 'Club house / Community Center', 'False Ceiling Lighting', 'Feng Shui / Vaastu Compliant', 'Fitness Centre / GYM', 'High Ceiling Height', 'Intercom Facility', 'Internet/wi-fi connectivity', 'Lift(s)', 'Low Density Society', 'Maintenance Staff', 'Natural Light', 'No open drainage around', 'Park', 'Piped-gas', 'Power Back-up', 'Private Garden / Terrace', 'Rain Water Harvesting', 'Recently Renovated', 'Security / Fire Alarm', 'Security Personnel', 'Separate entry for servant room', 'Shopping Centre', 'Spacious Interiors', 'Swimming Pool', 'Visitor Parking', 'Waste Disposal', 'Water Storage', 'Water purifier', 'Water softening plant']

In [ ]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
import ast
import re

# Step 1: Load data


# Step 2: Clean and parse furnishDetails
def parse_furnish_details(val):
    if pd.notnull(val) and val.startswith('['):
        try:
            items = ast.literal_eval(val)
            return [
                re.sub(r'^\d+\s+', '', item).strip()
                for item in items
                if isinstance(item, str) and not item.startswith('No')
            ]
        except:
            return []
    return []

df['furnish_list'] = df['furnishDetails'].apply(parse_furnish_details)

# Step 3: Binarize
mlb = MultiLabelBinarizer()
furnish_matrix = mlb.fit_transform(df['furnish_list'])
furnish_df = pd.DataFrame(furnish_matrix, columns=mlb.classes_)

# Step 4: Define weights
weights = {
    'AC': 3,
    'Bed': 2,
    'Chimney': 1,
    'Curtains': 1,
    'Dining Table': 2,
    'Exhaust Fan': 1,
    'Fan': 1,
    'Fridge': 2,
    'Geyser': 2,
    'Light': 1,
    'Microwave': 2,
    'Modular Kitchen': 3,
    'Sofa': 2,
    'Stove': 1,
    'TV': 2,
    'Wardrobe': 2,
    'Washing Machine': 2,
    'Water Purifier': 2
}

# Step 5: Compute luxury score
available_items = [item for item in weights.keys() if item in furnish_df.columns]
df['luxury_score'] = furnish_df[available_items].multiply(
    [weights[i] for i in available_items], axis=1
).sum(axis=1)

# Optional: check
print(df[['furnishDetails', 'luxury_score']].head())

                                                                                                                                                                                                                                                       furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
1       ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Geyser', '3 Light', '1 Curtains', '1 Chimney', '1 Modular Kitchen', 'No AC', 'No Bed', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']
2                                                                                                                                                                                                                                                                 NaN
3                                                                                                                                                                                                                                                                 NaN
4                                                                                                                                                                                                                                                                  []

   luxury_score
0             4
1            12
2             0
3             0
4             0

In [ ]:
luxury_score = df['luxury_score']

In [ ]:
luxury_score

0        4
1       12
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       9
13       0
14       0
15       1
16       0
17       0
18       0
19      11
20       0
21       7
22       0
23      11
24       0
25       0
26       4
27       0
28      11
29       0
30       1
31       0
32      10
33       5
34       0
35       1
36       0
37       0
38       2
39      11
40      15
41       3
42       0
43       0
44       7
45       0
46      10
47       7
48       4
49      23
50      13
51       9
52      25
53       0
54       3
55       7
56       9
57      11
58       4
59       9
60       3
61      10
62       0
63       1
64       0
65      12
66       0
67       0
68       0
69       0
70       1
71       0
72       0
73       0
74       9
75       0
76      11
77       0
78       0
79       0
80      21
81       0
82       0
83       7
84       2
85       0
86       5
87       0
88       5
89       7
90       1
91       0
92       0
93       0
94       0
95       1
96       0
97       0
98      12
99       3
100      0
101      8
102     12
103      0
104      0
105     10
106      0
107      0
108     25
109      4
110      0
111      0
112      0
113      0
114      0
115     16
116      0
117      0
118     19
119      0
120      0
121      0
122      0
123      0
124     16
125      0
126      0
127      0
128      0
129      0
130      5
131      0
132      0
133      9
134     11
135      0
136      1
137     10
138      0
139      0
140      0
141      7
142      0
143      7
144     14
145      4
146      1
147      0
148      0
149     15
150      0
151      0
152      0
153      0
154      0
155      2
156      9
157      1
158      0
159      0
160      0
161      0
162      0
163     21
164     10
165     17
166      1
167      0
168      0
169     13
170      0
171      0
172      1
173      4
174      3
175      0
176      0
177      0
178      0
179      0
180     12
181      0
182      0
183      0
184      0
185      0
186      0
187      4
188      8
189      0
190      0
191      0
192      0
193      0
194      0
195     20
196      1
197      1
198      0
199      1
200      0
201      1
202      1
203      0
204     12
205      0
206      1
207      5
208      8
209      0
210      0
211      0
212      5
213      8
214     21
215     23
216      7
217      4
218      0
219      9
220      0
221     16
222      0
223      1
224     16
225      6
226     10
227      0
228      0
229      0
230      0
231      0
232      0
233      0
234      7
235      0
236     14
237      0
238     10
239      0
240     10
241      0
242      6
243      0
244      9
245      6
246     12
247      0
248      0
249     10
250     13
251      4
252      0
253      0
254      0
255     12
256      2
257      0
258      8
259      0
260      0
261      0
262      0
263      0
264      0
265     11
266      0
267      0
268      0
269     11
270      0
271      6
272      0
273     10
274      0
275      0
276      0
277      6
278      1
279      4
280      0
281      1
282      4
283      4
284      0
285      4
286     12
287      0
288     24
289     30
290     14
291      9
292     20
293      0
294      0
295      0
296      0
297     12
298      0
299      3
300      8
301      0
302     13
303     14
304     22
305      0
306      3
307      0
308     14
309      0
310      2
311      0
312      3
313      1
314     14
315     10
316      0
317      0
318     16
319      0
320     24
321     30
322     14
323      0
324      0
325     12
326      3
327      8
328      0
329     13
330     14
331     22
332      0
333      3
334     14
335      2
336      3
337     14
338     10
339      0
340      8
341      0
342      8
343     13
344      8
345     11
346      0
347     20
348     16
349      8
350      8
351      0
352      0
353     11
354     12
355      0
356      8
357     11
358      8
359      5
360     10
361      0
362      0
363      0
364      0
365     13
366     20
367     10
368     12
369      5
370      0
371      0
372      8
373      0
374     18
375      0
376     23
377      0
378      6
379      0
380      0
381     10
382     18
383     18
384     20
385     11
386     12
387     28
388     21
389      7
390      0
391      2
392     14
393     12
394      0
395      8
396     15
397      0
398      0
399      7
400      3
401     11
402      7
403     18
404      6
405      4
406      4
407      0
408     13
409      0
410      2
411     20
412     19
413      2
414      6
415      9
416     10
417      8
418     11
419     13
420     11
421     11
422      0
423      0
424     13
425     11
426     15
427      9
428      6
429     12
430      0
431     10
432     13
433      8
434      0
435     10
436      0
437      0
438     13
439     13
440      7
441      9
442     11
443      0
444      0
445     14
446      0
447      6
448     14
449     15
450      5
451      0
452     27
453     27
454     15
455     11
456     15
457      3
458      0
459     20
460     14
461     17
462      0
463     11
464      5
465     14
466      0
467      0
468     14
469      0
470      0
471      9
472      7
473     20
474     11
475      9
476     11
477     13
478      2
479     10
480      0
481     18
482     18
483     18
484     17
485      0
486      0
487      0
488      4
489      0
490      0
491      0
492      3
493      3
494     13
495     13
496     11
497      0
498      5
499      9
500      3
501      3
502      3
503      3
504      3
505      3
506     20
507     18
508     14
509     14
510      7
511      7
512      7
513     15
514     10
515     21
516     21
517     21
518      1
519     21
520      8
521     13
522     15
523     11
524     13
525      9
526     10
527     10
528      0
529      2
530      2
531      2
532      5
533      0
534      0
535     11
536     16
537     19
538      0
539     11
540      0
541      0
542      3
543      3
544      8
545     19
546     13
547     11
548     12
549      0
550      0
551      3
552      0
553      0
554      0
555     15
556     16
557      0
558     24
559     14
560      2
561      7
562      7
563     14
564     13
565     10
566     23
567     23
568     23
569      7
570     23
571      8
572      0
573      6
574      7
575     12
576      0
577      0
578     10
579     30
580     26
581      4
582      7
583     15
584     11
585      3
586      0
587     12
588      4
589     11
590      0
591      0
592      0
593      9
594      0
595      0
596      0
597      0
598      0
599      0
600      1
601     10
602     12
603     32
604     16
605      0
606      0
607      0
608     14
609     11
610      3
611     11
612     16
613      1
614      1
615     10
616     16
617      0
618      9
619      0
620     15
621     27
622      5
623     11
624      7
625     11
626      0
627      3
628      0
629      1
630      6
631      0
632     12
633     11
634     11
635      0
636      0
637      8
638     12
639      0
640     10
641      0
642      0
643      0
644      0
645      0
646     14
647     16
648     16
649     16
650     22
651     22
652     20
653     12
654     15
655     13
656     20
657     16
658     10
659      0
660     10
661     30
662     30
663      4
664      0
665     11
666      0
667     14
668     15
669      6
670      2
671      0
672     12
673      0
674     11
675     14
676      4
677      8
678      3
679     12
680     22
681      0
682      9
683      5
684     14
685     10
686      9
687     10
688     11
689      0
690     12
691     18
692     17
693     18
694      5
695      0
696     11
697      0
698      1
699      1
700      6
701     11
702     16
703      3
704     16
705     32
706      0
707      0
708      0
709      0
710      0
711      0
712      0
713      0
714      0
715      0
716      0
717      0
718      0
719      0
720      0
721      4
722      0
723      0
724      0
725      8
726      0
727      4
728      6
729      0
730     14
731     22
732      5
733      0
734      9
735     15
736     15
737     13
738      8
739      8
740      9
741     11
742      4
743     14
744     13
745     12
746     12
747      2
748      0
749     16
750     14
751      0
752      0
753     12
754     16
755     16
756     16
757      4
758     16
759      0
760      8
761     16
762     16
763     15
764     14
765      0
766     11
767      8
768     18
769      9
770      9
771     16
772     21
773     10
774      0
775     12
776      0
777     18
778      0
779     14
780      0
781     16
782     15
783     22
784     11
785      5
786     11
787     10
788     20
789     11
790      0
791      0
792      0
793     15
794      0
795     10
796      7
797      0
798      9
799      3
800     12
801      6
802      6
803      2
804      2
805      6
806      6
807      6
808      0
809      0
810      0
811      0
812      0
813      0
814      0
815      0
816      0
817      0
818      0
819      0
820      0
821      0
822      0
823      3
824      3
825      7
826      7
827      3
828      3
829     22
830     24
831      0
832      0
833      6
834     16
835     11
836     17
837     11
838     11
839     11
840     16
841     24
842     11
843      7
844     15
845     14
846     11
847      0
848      0
849      0
850      0
851     16
852     14
853     17
854      2
855     11
856      0
857      0
858      2
859     11
860     11
861     16
862      3
863     12
864      9
865     11
866      9
867      2
868      9
869      6
870      7
871     13
872     12
873      9
874      5
875      8
876      0
877     10
878     14
879     12
880     10
881     11
882     14
883     14
884     14
885     11
886     13
887     13
888      3
889      9
890     11
891      9
892     11
893      9
894      5
895     10
896      0
897      9
898     10
899      6
900     10
901     13
902     10
903      0
904      0
905      0
906      4
907      5
908      2
909      6
910     20
911      0
912      0
913      0
914      0
915      8
916      0
917      0
918     12
919      0
920      0
921      0
922      0
923      0
924     10
925      9
926      6
927      3
928     11
929      0
930     17
931      0
932     10
933     12
934      0
935      7
936     15
937      9
938      7
939     11
940      9
941      0
942      0
943     16
944     14
945     14
946      0
947      0
948      0
949     12
950     11
951     15
952     13
953     23
954     11
955      0
956      7
957     16
958      0
959      0
960     15
961     15
962      1
963      1
964      5
965      3
966      3
967      2
968      3
969      1
970      1
971      2
972      1
973      0
974      6
975      1
976      1
977      2
978     32
979     10
980     11
981      5
982      9
983     12
984      0
985      3
986      3
987      3
988      6
989     10
990     11
991     11
992     11
993      0
994     15
995     12
996     10
997      7
998     15
999      0
1000    11
1001     0
1002     0
1003     0
1004     3
1005     0
1006     0
1007    15
1008     0
1009     0
1010     0
1011     0
1012     0
1013     0
1014     0
1015     0
1016     0
1017    11
1018     9
1019    14
1020    28
1021     1
1022    17
1023    17
1024    14
1025    11
1026    17
1027    21
1028    18
1029    20
1030    23
1031     6
1032    20
1033     0
1034     0
1035     0
1036    12
1037     2
1038    11
1039    14
1040    12
1041     0
1042     4
1043     7
1044    10
1045     9
1046    13
1047    13
1048    30
1049     0
1050    12
1051     9
1052    15
1053    14
1054    23
1055     0
1056    13
1057    13
1058    11
1059    14
1060     3
1061    10
1062     0
1063    32
1064     0
1065    17
1066     0
1067    12
1068    14
1069    12
1070    11
1071    15
1072    15
1073    15
1074     0
1075    16
1076    16
1077     0
1078    15
1079    19
1080     0
1081    16
1082    15
1083    15
1084    15
1085    15
1086    15
1087    17
1088    27
1089     7
1090    12
1091    12
1092    15
1093    15
1094     0
1095     2
1096    13
1097     0
1098    10
1099    17
1100    17
1101    17
1102     8
1103    18
1104    12
1105    14
1106    16
1107    16
1108    12
1109    11
1110     0
1111     0
1112     5
1113    10
1114     0
1115     0
1116     0
1117    11
1118    13
1119     3
1120     3
1121     3
1122    27
1123     0
1124     0
1125     0
1126     0
1127     0
1128     0
1129     8
1130     0
1131    15
1132     0
1133     3
1134     3
1135     3
1136     3
1137     3
1138     9
1139     3
1140     8
1141     9
1142    12
1143     0
1144     3
1145     3
1146     0
1147     0
1148     0
1149     2
1150    10
1151     0
1152    11
1153    11
1154    17
1155     8
1156     4
1157     8
1158     0
1159     0
1160     5
1161     0
1162     5
1163     0
1164     5
1165    10
1166     9
1167     0
1168    14
1169     0
1170     0
1171     0
1172    12
1173    10
1174     8
1175    11
1176     2
1177    14
1178     8
1179    15
1180    10
1181    20
1182    18
1183     0
1184     0
1185     0
1186    14
1187    22
1188     6
1189     6
1190     7
1191     6
1192     3
1193    10
1194    14
1195    17
1196    11
1197    13
1198     9
1199    12
1200     8
1201     0
1202     0
1203     0
1204     0
1205     0
1206    15
1207    12
1208    11
1209     0
1210     0
1211     0
1212     7
1213     0
1214     9
1215     6
1216     5
1217     5
1218     6
1219     0
1220     0
1221     0
1222     0
1223     0
1224     0
1225     4
1226     3
1227     3
1228     7
1229     1
1230     0
1231     0
1232     2
1233    11
1234     0
1235    15
1236    22
1237    22
1238     0
1239     0
1240     0
1241     0
1242     0
1243     0
1244     0
1245     0
1246     0
1247     0
1248     0
1249     0
1250     0
1251    16
1252     8
1253     9
1254     8
1255     9
1256     9
1257     0
1258     0
1259    21
1260    10
1261     0
1262     0
1263     0
1264    13
1265     3
1266    16
1267    14
1268    11
1269     0
1270     0
1271     0
1272     7
1273     2
1274    15
1275     4
1276     6
1277    16
1278    15
1279    21
1280     9
1281     8
1282    16
1283     2
1284     4
1285    11
1286    10
1287    11
1288    11
1289    14
1290    17
1291    22
1292    13
1293    13
1294    15
1295     0
1296     0
1297    16
1298    17
1299    23
1300    23
1301    14
1302    10
1303    23
1304    16
1305     0
1306     0
1307     0
1308     0
1309     0
1310     0
1311     0
1312     0
1313    17
1314    14
1315     0
1316     0
1317    14
1318     0
1319     0
1320     9
1321     0
1322    14
1323     9
1324    13
1325    14
1326     3
1327    15
1328     0
1329     7
1330    10
1331    10
1332    11
1333     0
1334     0
1335    12
1336     0
1337    10
1338     0
1339     0
1340     0
1341     0
1342     6
1343    11
1344     4
1345     9
1346     9
1347     7
1348     9
1349     9
1350    10
1351    12
1352    10
1353    10
1354    10
1355     9
1356    10
1357     8
1358    15
1359    14
1360     8
1361    11
1362     7
1363    15
1364    16
1365     0
1366    12
1367    14
1368    32
1369    15
1370    15
1371    32
1372    32
1373     8
1374     0
1375    10
1376     4
1377     5
1378     2
1379     9
1380    17
1381    12
1382    11
1383    11
1384    16
1385     0
1386    11
1387     3
1388     0
1389     0
1390     5
1391     5
1392     8
1393     7
1394     0
1395     0
1396     4
1397     9
1398     0
1399     0
1400     0
1401     0
1402     0
1403     5
1404     0
1405     0
1406     0
1407     0
1408     0
1409     0
1410     0
1411     0
1412     0
1413     0
1414     0
1415     8
1416    17
1417     0
1418     0
1419     0
1420     0
1421    12
1422    11
1423     0
1424     0
1425    10
1426    11
1427    11
1428     9
1429     4
1430     3
1431     7
1432     0
1433     0
1434     0
1435     0
1436     0
1437     6
1438     5
1439     5
1440     0
1441     6
1442     5
1443     0
1444     0
1445     0
1446     0
1447     0
1448     3
1449     6
1450     6
1451     0
1452     0
1453     0
1454    15
1455    16
1456    11
1457     6
1458    16
1459    15
1460    16
1461    16
1462    15
1463    13
1464     0
1465     0
1466    18
1467    17
1468     6
1469    13
1470     6
1471     6
1472     6
1473     7
1474     0
1475    11
1476     0
1477     0
1478     6
1479     0
1480     0
1481     0
1482     6
1483     6
1484    14
1485     0
1486    10
1487     0
1488     0
1489     0
1490     0
1491     0
1492     3
1493    16
1494     6
1495    32
1496    15
1497    28
1498    10
1499    16
1500    18
1501    13
1502    24
1503    14
1504     0
1505     0
1506    11
1507     7
1508    10
1509     8
1510     8
1511    11
1512     0
1513     6
1514     8
1515     0
1516    10
1517     5
1518     6
1519     3
1520     3
1521     3
1522     3
1523     3
1524     3
1525     3
1526     3
1527     3
1528     3
1529     3
1530     3
1531     3
1532     3
1533     3
1534     3
1535     0
1536     0
1537     0
1538     0
1539     0
1540     0
1541     8
1542    14
1543    13
1544    13
1545     0
1546    13
1547     9
1548     0
1549     9
1550    11
1551    14
1552    13
1553    12
1554    12
1555     7
1556     8
1557    24
1558     6
1559     4
1560     4
1561     4
1562     4
1563     4
1564     4
1565     4
1566     4
1567     4
1568     5
1569     4
1570    23
1571     7
1572     6
1573     6
1574    15
1575    15
1576    15
1577    15
1578    16
1579    14
1580     4
1581    11
1582     6
1583     7
1584     6
1585     3
1586    13
1587     8
1588     6
1589    14
1590     8
1591     0
1592    16
1593    10
1594    11
1595     7
1596    15
1597     7
1598     0
1599     0
1600    25
1601     7
1602     6
1603     0
1604     0
1605     0
1606     3
1607    14
1608     9
1609    10
1610     8
1611    13
1612    14
1613    13
1614     8
1615    14
1616    17
1617    11
1618    17
1619    16
1620    14
1621    12
1622    17
1623    10
1624     0
1625     1
1626     8
1627    11
1628     3
1629    12
1630    12
1631    10
1632     2
1633     2
1634     2
1635     2
1636     2
1637     0
1638     0
1639     2
1640     2
1641     0
1642     0
1643     2
1644     2
1645     2
1646     5
1647     1
1648     7
1649    15
1650    16
1651    17
1652     0
1653     0
1654    13
1655    18
1656     5
1657     9
1658     0
1659     0
1660     0
1661     0
1662     0
1663     6
1664     6
1665     5
1666     6
1667     3
1668     9
1669     8
1670     6
1671     9
1672     3
1673    11
1674    15
1675    12
1676     0
1677     0
1678     0
1679     3
1680     0
1681    12
1682    13
1683     7
1684    10
1685     2
1686     6
1687     9
1688     3
1689     8
1690     8
1691    11
1692     9
1693     8
1694     8
1695     8
1696    11
1697     0
1698    10
1699     5
1700     5
1701     7
1702     8
1703     0
1704     5
1705     0
1706    15
1707    15
1708     3
1709     3
1710     6
1711    12
1712    14
1713     3
1714    27
1715    11
1716     0
1717     0
1718     0
1719     0
1720     0
1721     0
1722     3
1723     3
1724     3
1725    15
1726    14
1727     3
1728     3
1729     3
1730     3
1731     3
1732     0
1733     0
1734     0
1735    15
1736     0
1737     0
1738     0
1739     0
1740    12
1741     0
1742    24
1743     7
1744     0
1745     0
1746     0
1747     3
1748     7
1749     0
1750    15
1751     5
1752     8
1753    14
1754     0
1755    11
1756    15
1757    14
1758     3
1759     3
1760     5
1761    16
1762     3
1763     4
1764     5
1765     5
1766     4
1767     3
1768    10
1769     3
1770     3
1771     3
1772    10
1773     3
1774     0
1775     3
1776     3
1777     3
1778    10
1779    10
1780    14
1781    15
1782     7
1783     0
1784    18
1785     0
1786     0
1787     0
1788     0
1789    11
1790     8
1791     0
1792     0
1793     0
1794     0
1795     3
1796     3
1797     3
1798     3
1799     3
1800     3
1801     5
1802     0
1803    11
1804    15
1805     5
1806     7
1807    24
1808     7
1809     8
1810    32
1811    15
1812     6
1813     0
1814     2
1815     1
1816     4
1817     4

In [ ]:
df.head()

,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,super_built_up_area,built_up_area,carpet_area,furnishing_type,features_list,furnish_list,luxury_score
0,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,Undefined,"['Chintapurni Mandir', 'State bank ATM', 'Pearl Dental Clinic', 'Taneja Hospital', 'Dr. Ashok Jain', 'Dr. Madan Clinic', 'Geeta Nursing Home Gurgaon', 'Chiranjiv Hospital', 'Dev Man Kathuria Clinic', 'Aryan Hospital', 'Kr Dental Hub', 'Swastik Maternity and Medical Centre', 'Satyam Hospital Gurgaon', 'Ravi Clinic and Health Care Centre', 'D.R. Rajnis Gupta Clinic', 'Esic Hospital Gurugram', 'Gurgaon Eye Centre', 'Bindal Clinic', 'Shiv Mahima Patient Care Bureau', 'Shree Krishna Hospital Gurgaon', 'M.S Hospital', 'My Care Clinic', 'Ankur Clinic and Maternity Home', 'Triveni Hospital Gurgaon', 'Shri Gobind Hospital', 'Navjeevan Hospital and Maternity Centre', 'Lal Superspeciality Hospital', 'Sparsh Hospital Gurgaon', 'Prateek Nursing Home And Polyclinic', 'Jain Sant Phool Chand Ji Charitable Hospital', 'Sarvodya Hospital', 'Bhatnagar Maternity and Nursing Home', 'Tirath Ram Hospitals Pvt Ltd', 'Dr. Sarvejeet Singh', 'Centre For Sight Gurgaon New Railway Road', 'Dr. Ajay S. Gupta Clinic', 'Kidney Clinic', 'Mangalam Hospital and Heart Centre Gurgaon', 'Sethi Hospital Gurgaon', 'Shubham Hospital Gurgaon', 'Kharbanda Maternity and Nursing Home', 'Gupta Hospital Gurgaon', 'Dentecare - Multispeciality Dental Clinic', 'State bank of india', 'Hdfc bank', 'Kotak bank', 'Indian bank', 'Pizza Hut', 'St. Michaels Sr. Sec. School', 'Dronacharya Government College']","So with lift.Maa bhagwati residency is one of gurgaon's most sought after destination for apartments and this 2 bhk flat in krishna colony is your opportunity to be a part of this community. The flat occupies a carpet area of 900 sq.Ft. That consists of 2 bedrooms, 2 bathrooms and 1 balcony. This flat is situated on the top floor of this 4 floors tall residential building. This 1-5 years old property is available for immediate possession as the project is ready to move.","['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'No Bed', 'No Chimney', 'No Curtains', 'No Dining Table', 'No Exhaust Fan', 'No Geyser', 'No Modular Kitchen', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']","['Feng Shui / Vaastu Compliant', 'Security / Fire Alarm', 'Lift(s)', 'Water Storage', 'Visitor Parking']","['Environment4 out of 5', 'Safety4 out of 5', 'Lifestyle4 out of 5', 'Connectivity4 out of 5']",None,None,NaN,0,"[Feng Shui / Vaastu Compliant, Security / Fire Alarm, Lift(s), Water Storage, Visitor Parking]","[Fan, Light, Wardrobe]",4
1,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,Old Property,"['Chintapurni Mandir', 'Sheetla Mata Mandir', 'State bank ATM', 'Sneh Hospital Gurgaon', 'Jiya Clinic', 'Dr. Mittal Clinic', ""Dr. Anurag's Child Care Clinic"", 'Yashroop Medical Centre', 'Dr. Sindhu Clinic', 'Bhardwaj Hospital', 'Jain Sant Phool Chand Ji Charitable Hospital', 'Sarvodya Hospital', 'Dr. Hitesh Dawar', 'Prateek Nursing Home And Polyclinic', 'R K Hospital Gurgaon', 'Chirag Hospital Pvt. Ltd', 'Kr Dental Hub', 'Gurgaon Eye Centre', 'Shree Krishna Hospital Gurgaon', 'Dr. Ashok Jain', 'GH Gurgaon', 'Aryan Hospital', 'Dr. Agya Ram Sharma Clinic', 'Pearl Dental Clinic', 'D.R. Rajnis Gupta Clinic', 'Sparsh Hospital Gurgaon', 'Bhatnagar Maternity and Nursing Home', 'Geeta Nursing Home Gurgaon', 'Taneja Hospital', 'Ravi Clinic and Health Care Centre', 'Dr. Sarvejeet Singh', 'Esic Hospital Gurugram', 'Centre For Sight Gurgaon New Railway Road', 'Kidney Clinic', 'Jackson Hospital', 'Jeevan Jyoti Hospital Gurgaon', 'Chiranjiv Hospital', 'Dr. Tomar Clinic', 'Indian bank', 'Kotak bank', 'Hdfc bank', 'State bank of india', 'Pizza Hut', 'St. Michaels Sr. Sec. School', 'Lieutenant Atul Kataria School', 'Dronacharya Government College', 'Gurgaon railway station', 'Gurgaon railway station', 'Gurgaon railway station']","Property situated on main road, railway station just 500mtrs, rajeev chowk just 2km, extraordinary security and very good connectivity for entire ncr","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Geyser', '3 Light', '1 Curtains', '1 Chimney', '1 Modular Kitchen', 'No AC', 'No Bed', 'No Dining Table', 'No Microwave', 'No Fridge', 'No Sofa', 'No Stove', 'No TV', 'No Washing Machine', 'No Water Purifier']","['Security / Fire Alarm', 'Maintenance Staff', 'Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Safety4 out of 5', 'Lifestyle4 out of 5', 'Connectivity5 out of 5']",None,None,NaN,1,"[Security / Fire Alarm, Maintenance Staff, Water Storage, Park, Visitor Parking]","[Wardrobe, Fan, Exhaust Fan, Geyser, Light, Curtains, Chimney, Modular Kitchen]",12
2,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3,not available,"Sohna, Gurgaon, Haryana",12.0,NaN,new Property,"['Huda City Metro', 'Golf Course extn road', 'Rajiv Chowk', 'IGI Airport', 'IMT Sohna', 'Damdama Lake']","This property is 15 km away from badshapur, gurugram.It's under tunsiani construction call easy in homes right on sohna highway, hardly away from toll plaza...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Compliant', 'Intercom Facility', 'Lift(s)', 'Swimming Pool', 'Park', 'Fitness Centre / GYM', 'Club house / Community Center']","['Environment4 out of 5', 'Safety4 out of 5', 'Lifestyle4 out of 5', 'Connectivity5 out of 5']",None,None,NaN,0,"[Power Back-up, Feng Shui / Vaastu Compliant, Intercom Facility, Lift(s), Swimming Pool, Park, Fitness Centre / GYM, Club house / Community Center]",[],0
3,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2.0,2.0,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Undefined,"['Sector 55-56 Metro station', 'Bestech Central Square Mall', 'Golf Course Ext Road', 'Badshahpur Sohna Rd Hwy', 'ORCHIDS The International School', 'Sushant University', 'Marengo Asia Hospitals', 'Indira Gandhi Intl Airport', 'Gurgaon Railway Station']",Near to metro station of sector 56 and opposite leading 5 star hotel - Hyatt. Posh locality\nPrices negotiable,NaN,"['Security / Fire Alarm', 'Private Garden / Terrace', 'Lift(s)', 'Maintenance Staff', 'False Ceiling Lighting', 'Water Storage', 'Visitor Parking', 'Swimming Pool', 'Natural Light', 'Airy Rooms', 'Fitness Centre / GYM', 'Club house / Community Center', 'Water softening plant']",NaN,None,None,NaN,0,"[Security / Fire Alarm, Private Garden / Terrace, Lift(s), Maintenance Staff, False Ceiling Lighting, Water Storage, Visitor Parking, Swimming Pool, Natural Light, Airy Rooms, Fitness Centre / GYM, Club house / Community Center, Water softening plant]",[],0
4,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2.0,2.0,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. Sarkar Clinic', 'Sagar Clinic', 'Orris Community Center', 'Vijay Petrol Pump', 'HP Petrol Pump', 'Essar Petrol Pump', 'Indian Oil', 'Pizza Hut', 'KFC']","We are the proud owners of this 2 bhk alongwith 1 study room apartment available in parkwood westend, sector-92, gurgaon. This apartmentit is a resale and the unit is located on the 5th floor and has a super built-Up area of 1345. 0 sq. Ft. It has 2 bathroom(s) and 3 balcony(s). The ownership is freehold type. The apartment has 1 covered parking and 1 open parking.",[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', 'Lifestyle4 out of 5', 'Connectivity4 out of 5']",None,None,NaN,0,[],[],0

In [ ]:
df.drop(columns=['nearbyLocations','furnishDetails','features','additionalRoom'],inplace=True)

In [ ]:
df.sample(5)

,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,address,floorNum,facing,agePossession,description,rating,super_built_up_area,built_up_area,carpet_area,furnishing_type,features_list,furnish_list,luxury_score
1409,orris aster court premier,1.45,6839.0,2120.0,Super Built up area 2120(196.95 sq.m.)Built Up area: 1616 sq.ft. (150.13 sq.m.),3.0,4.0,2,"147, Sector 85 Gurgaon, Gurgaon, Haryana",3.0,North,new Property,"Check out this 3 bhk apartment for sale in orris aster court premier, a popular residential project that houses in-Demand flats in sector 85 gurgaon. This property faces the north direction. The floor plan additionally contains 3 bedroom(s), 4 bathrooms and 2 balconies. All in all, the flat is spread over a super built up area of 2120 sq.Ft. This flat lies on the 3rd level of a 12 storey building. Being a ready to move project, you can expect immediate possession of this 0-1 year old property. Orris aster court premier is designed very well to provide modern facilities such as swimming pool and fitness centre / gym.","['Environment5 out of 5', 'Lifestyle5 out of 5', 'Connectivity5 out of 5', 'Safety4.5 out of 5']",None,None,NaN,0,"[Swimming Pool, Fitness Centre / GYM]",[],0
1412,dlf regal gardens★,1.75,7900.0,2215.0,Super Built up area 2215(205.78 sq.m.),4.0,4.0,3+,"347, Sector 90 Gurgaon, Gurgaon, Haryana",3.0,East,Undefined,"Located in the popular residential address of sector 90 gurgaon, dlf regal gardens is one of the most preferred destination for apartments in gurgaon. This 4 bhk flat is your ticket to be a part of this community. Constructed on a super built up area of 2215 sq.Ft., the flat comprises 4 bedroom(s), 4 bathrooms and more than 3 balconies. The property is located on the 3rd floor of a 29 floors tall building. As the project is already ready to move, so you can easily move into this 1-5 years old property.","['Green Area5 out of 5', 'Construction4.5 out of 5', 'Management4 out of 5', 'Amenities5 out of 5', 'Connectivity4 out of 5']",None,None,NaN,0,"[Lift(s), Maintenance Staff]",[],0
1961,smart world gems,1.05,9519.0,1103.0,Built Up area: 1103 (102.47 sq.m.),2.0,2.0,2,"Sector 89 Gurgaon, Gurgaon, Haryana",4.0,NaN,Under Construction,Most prime location of new gurgaon,"['Environment4 out of 5', 'Lifestyle4 out of 5', 'Connectivity4 out of 5', 'Safety4 out of 5']",None,None,NaN,0,"[Power Back-up, Intercom Facility, Lift(s), Swimming Pool, Park, Piped-gas, Internet/wi-fi connectivity, Fitness Centre / GYM, Club house / Community Center]",[],0
1851,shree vardhman flora★,0.66,5076.0,1300.0,Super Built up area 1300(120.77 sq.m.)Carpet area: 960 sq.ft. (89.19 sq.m.),2.0,2.0,3,"C1405, Sector 90 Gurgaon, Gurgaon, Haryana",4.0,North-East,Undefined,"Situated in sector 90 gurgaon, shree vardhman flora is a well planned society that offers a pleasant living experience to its residents. This 2 bhk flat in gurgaon is your opportunity to be a part of this community. The flat is north-East-Facing. The flat occupies a super built up area of 1300 sq.Ft. That consists of 2 bedrooms, 2 bathrooms and 3 balconies. The residential building has 13 floors in total and the flat for sale is located on the 4th floor. This is a ready to move project and the property is 1-5 years old. The flat comes well built with ceramic flooring options. Many of the modern amenities being offered, like swimming pool, shopping centre, cctv surveillance, club house / community center, fitness centre / gym, park, lift(s), maintenance staff, visitor parking, water softening plant and security personnel, will provide a pleasant living experience for you. Municipal corporation and borewell/tank provides a regular supply of water to this residential project.\n Additional details :Piped gas facility is available in the property.\nThe apartment has borings water supply.\nDaily needs shopping could be done within the society premises to make the stay convinent.\nFull power backup is available.\nThere is also a separate washroom for domestic help.\nThe society has dedicated security guards for every tower.","['Green Area5 out of 5', 'Construction5 out of 5', 'Management4 out of 5', 'Amenities5 out of 5', 'Connectivity5 out of 5']",None,None,NaN,0,"[Security / Fire Alarm, Power Back-up, Feng Shui / Vaastu Compliant, Intercom Facility, Lift(s), High Ceiling Height, Maintenance Staff, Water Storage, No open drainage around, Visitor Parking, Swimming Pool, Park, Security Personnel, Natural Light, Internet/wi-fi connectivity, Airy Rooms, Shopping Centre, Fitness Centre / GYM, Waste Disposal, Rain Water Harvesting, Club house / Community Center, Water softening plant]",[],0
2849,signature global solera★,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Undefined,NaN,NaN,None,None,NaN,0,[],[],0

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df['property_type'].value_counts().plot(kind='bar')

KeyError: 'property_type'

In [ ]:
df['property_type'] = np.random.choice(['House', 'Flat'], size=len(df))

In [ ]:
df['property_type']

In [ ]:
df['society'].value_counts()

In [ ]:
df[df['society'] !='independent']['society'].value_counts(normalize=True).cumsum().head(75)

In [ ]:
society_counts = df['society'].value_counts()

frequency_bins = {
    "Very High (>100)": (society_counts > 100).sum(),
    "High (50-100)":((society_counts >=50) & (society_counts<=100)).sum(),
    "Average (10-40)":((society_counts >=10) & (society_counts<50)).sum(),
    "Low (2-9)":((society_counts > 1) & (society_counts <10)).sum(),
    "Very Low (1)":(society_counts ==1).sum()
}
frequency_bins

In [ ]:
df[df['society'] != 'independent']['society'].value_counts().head(10).plot(kind='bar')

In [ ]:
df['society'].isnull().sum()

In [ ]:
df[df['society'].isnull()]

In [ ]:
df.drop('property_name', axis=1, inplace=True)

In [ ]:
df['price'].isnull().sum()

In [ ]:
sns.histplot(df['price'],kde=True, bins=50)

In [ ]:
df['price'].describe()

In [ ]:
skewness = df['price'].skew()
kurtosis = df['price'].kurt()
print(skewness,kurtosis)

In [ ]:
quantiles = df['price'].quantile([0.01,0.05,0.95,0.99])
quantiles

In [ ]:
ecdf =df['price'].value_counts().sort_index().cumsum() /len(df['price'])
plt.plot(ecdf.index,ecdf,marker = '.', linestyle='none')
plt.grid()

In [ ]:
plt.figure(figsize=(15,6))

plt.subplot(1,2,1)
sns.histplot(df['price'],kde=True, bins=50,color='skyblue')
plt.title('Distribution of Prices (Orginal)')

In [ ]:
df['price_per_sqft'].describe()

In [ ]:
sns.histplot(df['price_per_sqft'],bins=50, color='skyblue',kde=True)

In [ ]:
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1-1.5*IQR
upper_bound = Q3-1.5*IQR
outliers = df[(df['price'] < lower_bound) | (df['price'] > upper_bound)]

In [ ]:
num_outliers = outliers.shape[0]
outliers_price_stats = outliers['price'].describe()

num_outliers, outliers_price_stats

In [ ]:
outliers.sort_values('price',ascending=False).head(20)

In [ ]:

outliers_sqft['area'] = outliers_sqft['area'].apply(lambda x : x*9 if x<1000 else x)

In [ ]:
outliers_sqft = outliers_sqft.copy()


outliers_sqft['area'] = outliers_sqft['area'].apply(lambda x: x * 9 if x < 1000 else x)

In [ ]:
outliers_sqft = df[(df['price_per_sqft'] < lower_bound) | (df['price_per_sqft'] > upper_bound)]

num_outliers = outliers_sqft.shape[0]
outliers_sqft_stats = outliers_sqft['price_per_sqft'].describe()

In [ ]:
outliers_sqft = df[(df['price_per_sqft'] < lower_bound) | (df['price_per_sqft'] > upper_bound)]

In [ ]:
outliers_sqft['area'] = outliers_sqft['area'].apply(lambda x: x*9 if x<1000 else x)

outliers_sqft['price_per_sqft'] = round((outliers_sqft['price']*10000000)/outliers_sqft['area'])

In [ ]:
outliers_sqft['price_per_sqft'].describe()

In [ ]:
outliers_sqft['price_per_sqft'].describe()

In [ ]:
outliers_sqft['price_per_sqft'] = round((outliers_sqft['price']*10000000)/outliers_sqft['area'])

In [ ]:
df.update(outliers_sqft)

In [ ]:
import seaborn as sns
sns.distplot(df['price_per_sqft'])

In [ ]:
df[df['price_per_sqft']>50000]

In [ ]:
df=df[df['price_per_sqft'] <=5000]

In [ ]:
sns.boxplot(x=df['price_per_sqft'])

In [ ]:
df[df['area']>10000].sort_values('area',ascending=False)

In [ ]:
df['area'].describe()

In [ ]:
sns.distplot(df['bedRoom'])

In [ ]:
df['bedRoom'].describe()

In [ ]:
df['bedRoom'].describe()

In [ ]:
df[df['bedRoom'] > 3].sort_values('bedRoom',ascending=False)

In [ ]:
df = df[df['bedRoom'] <=10]

In [ ]:
df.shape

In [ ]:
sns.distplot(df['bedRoom'])

In [ ]:
df.head()

In [ ]:
df.head()

In [ ]:
import seaborn as sns
sns.lmplot(data=df,x='area',y='bedRoom')

In [ ]:
outliers_df = df[(df['area_room_ratio'] < 250) & (df['bedRoom'] >3)]

In [ ]:
df['area_room_ratio'] = df['area']/df['bedRoom']

In [ ]:
(df[df['area_room_ratio'] <250])['bedRoom'].value_counts()

In [ ]:
df.shape

In [ ]:
df = df[~((df['area_room_ratio'] <250) & (df['bedRoom'] > 4))]

In [ ]:
sns.lmplot(data=df,x='area',y='bedRoom')

In [ ]:
df.to_csv('property.csv',index=False)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:

pd.set_option('display.max_columns',None)

In [ ]:
df= pd.read_csv('property.csv')

In [ ]:
df.head()

In [ ]:
df.isnull().sum()

In [ ]:
all_present_df = df.dropna(subset=['super_built_up_area', 'built_up_area', 'carpet_area'])

In [ ]:
super_to_built_up_ratio = (all_present_df['super_built_up_area']/all_present_df['built_up_area']).median()

In [ ]:
carpet_to_built_up_ratio = (all_present_df['carpet_area']/all_present_df['built_up_area']).median()

In [ ]:
df['super_built_up_area']

In [ ]:
all_present_df.head()

In [ ]:
df['super_built_up_area'] = df['super_built_up_area'].astype(str).str.extract(r'(\d+\.?\d*)')
df['super_built_up_area'] = pd.to_numeric(df['super_built_up_area'], errors='coerce')
area_columns = ['super_built_up_area', 'built_up_area', 'carpet_area']


for col in area_columns:
    df[col] = df[col].astype(str).str.extract(r'(\d+\.?\d*)')
    df[col] = pd.to_numeric(df[col], errors='coerce')
# See first few values of each column
print(df[['super_built_up_area', 'built_up_area', 'carpet_area']].head())

# Count missing values
print(df[area_columns].isnull().sum())

In [ ]:
all_present_df = df.dropna(subset=area_columns)

In [ ]:
print(all_present_df)

In [ ]:
some_present_df = df.dropna(subset=['built_up_area'])

In [ ]:
print(df['super_built_up_area'].unique()[:20])

In [ ]:
raw_df = pd.read_csv('property.csv')
print(raw_df['super_built_up_area'].unique()[:20])

In [ ]:
sbc_df = df[~(df['super_built_up_area'].isnull()) & (df['built_up_area'].isnull()) & ~(df['carpet_area'].isnull())]

In [ ]:
sbc_df.head()

In [ ]:
all_present_df = df[
    (~df['super_built_up_area'].isnull()) &
    (~df['built_up_area'].isnull()) &
    (~df['carpet_area'].isnull())
]

In [ ]:
all_present_df

In [ ]:
df['super_built_up_area'].isnull()

In [ ]:
print(df['super_built_up_area'].isnull().sum())

In [ ]:
df['super_built_up_area']

In [ ]:
df['floorNum'].fillna(2,0,inplace=True)

In [ ]:
df['floorNum'].fillna(2, inplace=True)

In [ ]:
df.isnull().sum()

In [ ]:
df['facing'].value_counts().plot(kind='pie')

In [ ]:
df.shape

In [ ]:
df.drop(columns=['facing'],inplace=True)

In [ ]:
df.sample(5)

In [ ]:
df.isnull().sum()

In [ ]:
df[df['agePossession']=='Undefined']

In [ ]:

def mode_based_imputation(row):
    if row['agePossession'] == 'Undefined':
        mode_value = df[(df['sector'] ==row['sector']) & (df['property_type'])]['agePossession'].mode()
        if not mode_value.empty:
            return mode_value.iloc[0]
        else:
            return np.nan
    else:
        return row['agePossession']

In [ ]:
df['agePossession'].value_counts()

In [ ]:
def mode_based_imputation2(row):
    if row['agePossession'] == 'Undefined':
        mode_value = df[(df['sector'] == row['sector'])]['agePossession'].mode()

        if not Mode_value.empty:
            return mode_value.iloc[0]
        else:
            return np.nan
    else:
        return row['agePossession']

In [ ]:
df['agePossession'] = df.apply(mode_based_imputation2,axis=1)

In [ ]:
df.isnull().sum()

In [ ]:
df['area_room_ration'].fillna(df['area_room_ration'].mean(), inplace=True)
df['area_room_ratio'].fillna(df['area_room_ratio'].mean(), inplace=True)
df.dropna(subset=['area_room_ration', 'area_room_ratio'], inplace=True)

In [ ]:
# Numeric fills
df['price'].fillna(df['price'].median(), inplace=True)
df['price_per_sqft'].fillna(df['price_per_sqft'].median(), inplace=True)
df['area'].fillna(df['area'].median(), inplace=True)
df['bedRoom'].fillna(df['bedRoom'].mode()[0], inplace=True)
df['bathroom'].fillna(df['bathroom'].mode()[0], inplace=True)
df['balcony'].fillna(df['balcony'].mode()[0], inplace=True)

# Categorical fills
df['society'].fillna('Unknown', inplace=True)
df['address'].fillna('Unknown', inplace=True)
df['agePossession'].fillna('Unknown', inplace=True)
df['furnishDetails'].fillna('Not Available', inplace=True)
df['features'].fillna('Not Available', inplace=True)
df['description'].fillna('', inplace=True)

# Rating fill


# Drop columns with too many missing values
df.drop(['super_built_up_area', 'built_up_area', 'carpet_area'], axis=1, inplace=True)

In [ ]:
# Fill missing ratings with median
df['rating'].fillna(df['rating'].median(), inplace=True)

In [ ]:
df['rating'].fillna(df['rating'].mean(), inplace=True)

In [ ]:
df['rating'].fillna(df['rating'].median(), inplace=True)

In [ ]:
df.isnull().sum()

In [ ]:
df['nearbyLocations'] = df['nearbyLocations'].apply(lambda x: eval(x) if pd.notnull(x) else [])

In [ ]:
df['nearbyLocations'].fillna('Not Available', inplace=True)

In [ ]:
def categorize_luxury(score):
    if 0<=score <50:
        return "low"
    elif 50<=score <150:
        return "Medium"
    elif 150<= score <=175:
        return "High"
    else:
        return None

In [ ]:
train_df=df.drop(columns=['society','price_per_sqft'])

In [ ]:
train_df.head()

In [ ]:
train_df['luxury_category']=train_df['luxury_score'].apply(categorize_luxury)

In [ ]:
train_df.head()

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

data_label_encoded = train_df.copy()

categorial_cols = train_df.select_dtypes(include=['object']).columns

for col in categorial_cols:
  oe=OrdinalEncoder();
  data_label_encoded[col]=oe.fit_transform(data_label_encoded[[col]])
  print(oe.categories_)

x_label=data_label_encoded.drop('price',axis=1)
y_label=data_label_encoded['price']

In [ ]:
y_label=data_label_encoded['price']
y_label

In [ ]:
f1_df=data_label_encoded.corr()['price'].iloc[1:].to_frame().reset_index().rename(columns={'index':'feature','price':'corr_coeff'})
f1_df

In [ ]:
x_label=data_label_encoded.drop('price',axis=1)
from sklearn.ensemble import RandomForestRegressor

rf_label=RandomForestRegressor(n_estimators=100,random_state=42)
rf_label.fit(x_label,y_label)

fi_df2=pd.DataFrame({
    'feature':x_label.columns,
    'rf_importance': rf_label.feature_importances_}).sort_values(by='rf_importance',ascending=False)

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
gb_label = GradientBoostingRegressor()
gb_label.fit(x_label,y_label)

fi_df3=pd.DataFrame({
    'feature':x_label.columns,
    'gb_importance':gb_label.feature_importances}).sort_values(by='gb_importance',ascending=False)
fi_df3

In [ ]:
print(x_label.isnull().sum())

In [ ]:
x_label = x_label.dropna(subset=['super_built_up_area'])

# Drop rows with NaN in 'built_up_area'
x_label= x_label.dropna(subset=['built_up_area'])

# Drop rows with NaN in 'carpet_area'
x_label = x_label.dropna(subset=['carpet_area'])

# Drop rows with NaN in 'rating'
x_label = x_label.dropna(subset=['rating'])

In [ ]:
print(x_label.isnull().sum())

In [ ]:
x_label

In [ ]:
from sklearn.inspection import permutation_importance
from sklearn.model_selection import train_test_split

x_train_label, x_test_label,y_train_label,y_test_label = train_test_split(x_label,y_label,test_size=0.2,random_state=42)
rf_label = RandomForestRegressor(n_estimators=100, random_state=42)
rf_label.fit(x_train_label,y_train_label)

perm_importance = permutation_importance(rf_label,x_test_label,y_test_label,n_repeats=60,random_state=42)

fi_df4 = pd.DataFrame({'feature':X_label.columns,'permutation_importance':perm_importance.importances_mean}).sort_values(by='permutation_importance',ascending=False)
fi_df4

In [ ]:
x_label.dtypes

In [ ]:
x_label_clean = x_label.drop(columns=['features_list', 'furnish_list', 'property_type', 'luxury_category'])

In [ ]:
rf_label.fit(x_train_label, y_train_label)

In [ ]:
from sklearn.preprocessing import LabelEncoder

for col in ['property_type', 'luxury_category']:
    le = LabelEncoder()
    x_label[col] = le.fit_transform(x_label[col].astype(str))

In [ ]:
x_train_label, x_test_label, y_train_label, y_test_label = train_test_split(x_label, y_label, test_size=0.2, random_state=42)
rf_label.fit(x_train_label, y_train_label)

In [ ]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled=scaler.fit_transform(x_label)
lasso=Lasso(alpha=0.01,random_state=42)
lasso.fit(X_scaled,y_label)

fi_df5 = pd.DataFrame({
    'feature':x_label.columns,
    'lasso_coreff':lasso.coef_}).sort_values(by='lasso_coeff',ascending=False)
fi_dfs

In [ ]:
x_label_clean = x_label.drop(columns=['features_list', 'furnish_list'], errors='ignore')
x_label_numeric = x_label_clean.select_dtypes(include=['int64', 'float64', 'int32'])
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(x_label_numeric)

lasso = Lasso(alpha=0.01, random_state=42)
lasso.fit(X_scaled, y_label)

In [ ]:
from sklearn.linear_model import LinearRegression

lin_reg=LinearRegression()
lin_reg.fit(X_scaled,y_label)

fi_df7 = pd.DataFrame({
    'feature':x_label.columns,
    'reg_coeffs':lin_reg.coef_}).sort_values(by='reg_coeffs',ascending=False)
fi_df7

In [ ]:
# Drop rows with NaN from x_label and y_label
x_label_clean = x_label.dropna()
y_label_clean = y_label[x_label_clean.index]  # ensure y stays aligned

# Scale and fit again
X_scaled = scaler.fit_transform(x_label_clean)
lin_reg.fit(X_scaled, y_label_clean)

In [ ]:
from sklearn.impute import SimpleImputer

# Impute missing values with mean (or median)
imputer = SimpleImputer(strategy='mean')
x_label_imputed = imputer.fit_transform(x_label)

# Then scale and fit
X_scaled = scaler.fit_transform(x_label_imputed)
lin_reg.fit(X_scaled, y_label)

In [ ]:
x_label = x_label.drop(columns=['features_list', 'furnish_list'])  # or whichever columns show lists

In [ ]:
features_df = pd.DataFrame(x_label['features_list'].tolist()).fillna(0)
x_label = x_label.drop(columns=['features_list'])
x_label = pd.concat([x_label, features_df], axis=1)

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

imputer = SimpleImputer(strategy='mean')
x_label_imputed = imputer.fit_transform(x_label)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(x_label_imputed)

lin_reg.fit(X_scaled, y_label)

In [ ]:
y_label.isnull()

In [ ]:
import pandas as pd

# Combine x_label and y_label into a DataFrame
df = pd.DataFrame(x_label)
df['target'] = y_label

# Drop rows where y_label is NaN
df = df.dropna(subset=['target'])

# Separate them back
x_label_clean = df.drop(columns='target')
y_label_clean = df['target']

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=42)
scores = cross_val_score(rf, x_label_clean, y_label_clean, cv=5, scoring='r2')

In [ ]:
scores.mean()

In [ ]:
rf=RandomForestRegressor(n_estimators=100,random_state=42)
scores = cross_val_score(rf,x_label.drop(columns=['pooja room','study room','others']),y_label,cv=5,scoring='r2')

In [ ]:
print(x_label.columns)

In [ ]:
export_df.to_csv('property.csv',index=False)

In [ ]:
export_df = x_label.drop(columns=['pooja room', 'study room', 'others'], errors='ignore')

In [ ]:
export_df['price']=y_label

In [ ]:
y_label

In [ ]:
export_df.head()

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('property.csv')

In [ ]:
df.head()

In [ ]:
X=df.drop(['price'],axis=1)

In [ ]:
y=df['price']

In [ ]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [ ]:
columns_to_encode = ['balcony','agePossession']

In [ ]:
y_transformed=np.log1p(y)

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num',StandardScaler(),['bedRoom','bathroom','built_up_area']),
        ('cat',OneHotEncoder(drop='first'),columns_to_encode)],
    remainder='passthrough'
)

In [ ]:
pipeline=Pipeline([
    ('preprocessor',preprocessor),
    ('regressor',LinearRegression())
])

In [ ]:
kfold=KFold(n_splits=10,shuffle=True,random_state=42)

In [ ]:
kfold=KFold(n_splits=10,shuffle=True,random_state=42)

scores=cross_val_score(pipeline,X,y_transformed,cv=kfold,scoring='r2')

In [ ]:
scores.std()

In [ ]:
X = X.fillna(0)
y_transformed = y_transformed.fillna(0)

In [ ]:
# All columns you want to convert that should be numeric
numeric_cols = [
    'price_per_sqft', 'area', 'bedRoom', 'bathroom', 'balcony', 'floorNum',
    'super_built_up_area', 'built_up_area', 'carpet_area',
    'Fan', 'Stove', 'Wardrobe', 'Fridge', 'AC', 'Chimney', 'TV', 'Light',
    'Washing Machine', 'Dining Table', 'Microwave', 'Sofa', 'Water Purifier',
    'Geyser', 'Bed', 'Curtains'
]

# Now apply to_numeric only on these columns
X[numeric_cols] = [numeric_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
pipeline.fit(x_train,y_train)

In [ ]:
print("NaNs in x_train:", x_train.isna().sum().sum())
print("NaNs in y_train:", y_train.isna().sum())

In [ ]:
# Fill NaNs in both x and y before splitting


print(x.columns)
print(x.dtypes)

In [ ]:
x_test=x_test.drop(['areaWithType'],axis=1)

In [ ]:
y_transformed.head()

In [ ]:
y_pred = pipeline.predict(x_test)

In [ ]:
y_pred = np.expm1(y_pred)

In [ ]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(np.expm1(y_test),y_pred)

In [ ]:
def scorer(model_name,model):
    output = []
    output.append(model_name)
    pipeline=Pipeline([
    ('preprocessor',preprocessor),
    ('regressor',model)
    ])
    kfold=KFold(n_splits=10,shuffle=True,random_state=42)
    scores=cross_val_score(pipeline,X,y_transformed,cv=kfold,scoring='r2')
    output.append(scores.mean())
    x_train,x_test,y_train,y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    pipeline.fit(x_train,y_train)
    y_pred=pipeline.predict(x_test)
    y_pred = np.expm1(y_pred)
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    return output

In [ ]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor  # Requires `xgboost` to be installed

model_dict={
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Lasso(),
    'decision tree':DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra tress':ExtraTreesRegressor(),
    'gradient boosting':GradientBoostingRegressor(),
    'adaboost':AdaBoostRegressor(),
    'mlp':MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [ ]:
model_output = []
for model_name, model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [ ]:
model_output

In [ ]:
model_df = pd.DataFrame(model_output,columns=['name','r2','mae'])

In [ ]:
model_df.sort_values(['mae'])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers = [
        ('num',StandardScaler(),['bedRoom','bathroorm','built_up_area']),
        ('cat',OrdinalEncoder(),columns_to_encode),
        ('cat1',OneHotEncoder(drop='first'),['agePossession'])
    ],
    remainder = 'passthrough'
)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers = [
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1', OneHotEncoder(drop='first'), ['agePossession'])
    ],
    remainder = 'passthrough'
)

In [ ]:
from sklearn.model_selection import KFold, cross_val_score
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline,X,y_transformed,cv=kfold,scoring='r2')

In [ ]:
scores.mean()

In [ ]:
scores.std()

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [ ]:
pipeline.fit(x_train,y_train)

In [ ]:
y_pred =pipeline.predict(x_test)

In [ ]:
y_pred= np.expm1(y_pred)

In [ ]:
mean_absolute_error(np.expm1(y_test),y_pred)

In [ ]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'regressor__n_estimators':[50,100,200,300],
    'regressor__max_depth':[None,10,20,30],
    'regressor__max_samples':[0.1,0.25,0.5,1.0],
    'regressor__max_features':['auto','sqrt']
}

In [ ]:
import category_encoders as ce
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

columns_to_encode = ['property_type', 'balcony', 'agePossession', 'floor_category']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1', OneHotEncoder(drop='first', sparse_output=False), ['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['some_column'])  # Replace 'some_column' with your actual target-encoded column
    ],
    remainder='passthrough'
)

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1', OneHotEncoder(drop='first', sparse_output=False), ['agePossession'])],
    remainder='passthrough'
)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

pipeline=Pipeline([
    ('preprocessor',preprocessor),
    ('regressor',RandomForestRegressor(n_estimators=500))
])